/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout User */
        post: operations["logout_user_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/set-current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Event As Current */
        post: operations["set_event_as_current_schedule_set_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move Schedule Event */
        post: operations["move_schedule_event_schedule_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/set-skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Schedule Event Skip */
        post: operations["set_schedule_event_skip_schedule_set_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule Changes */
        get: operations["get_schedule_changes_schedule_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/changes/{schedule_change_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo Schedule Change */
        delete: operations["undo_schedule_change_schedule_changes__schedule_change_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Subscription */
        post: operations["new_subscription_schedule_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subscription */
        delete: operations["delete_subscription_schedule_subscriptions__subscription_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voting/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voting Status */
        get: operations["get_voting_status_voting_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voting/nominations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voting Nominations */
        get: operations["list_voting_nominations_voting_nominations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voting/nominations/{nomination_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voting Nominations */
        get: operations["list_voting_nominations_voting_nominations__nomination_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voting/nominations/{nomination_id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add Vote */
        put: operations["add_vote_voting_nominations__nomination_id__vote_put"];
        post?: never;
        /** Cancel Vote */
        delete: operations["cancel_vote_voting_nominations__nomination_id__vote_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/tcloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Tcloud Order */
        post: operations["process_tcloud_order_webhooks_tcloud_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddVoteRequest */
        AddVoteRequest: {
            /** Participant Id */
            participant_id: number;
        };
        /** AddVoteResponse */
        AddVoteResponse: {
            /** Vote Id */
            vote_id: number;
        };
        /** Body_login_for_access_token_auth_token_post */
        Body_login_for_access_token_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CreateSubscriptionRequest */
        CreateSubscriptionRequest: {
            /** Event Id */
            event_id: number;
            /** Counter */
            counter: number;
        };
        /** FullUserDTO */
        FullUserDTO: {
            /** Id */
            id: number;
            /** Tg Id */
            tg_id: number | null;
            /** Username */
            username: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            role: components["schemas"]["UserRole"];
            settings: components["schemas"]["UserSettings"];
            ticket: components["schemas"]["UserTicketDTO"] | null;
            /** Permissions */
            permissions: components["schemas"]["UserPermissionDTO"][];
        };
        /** GetScheduleResponse */
        GetScheduleResponse: {
            /** Schedule */
            schedule: components["schemas"]["ScheduleEventDTO"][];
        };
        /** GetVotingStateResponse */
        GetVotingStateResponse: {
            /** Can Vote */
            can_vote: boolean;
            status: components["schemas"]["VotingStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListScheduleChangesResponse */
        ListScheduleChangesResponse: {
            /** Schedule Changes */
            schedule_changes: components["schemas"]["ScheduleChangeDTO"][];
        };
        /** ListVotingNominationsResponse */
        ListVotingNominationsResponse: {
            /** Nominations */
            nominations: components["schemas"]["NominationVotingDTO"][];
        };
        /** MoveScheduleEventRequest */
        MoveScheduleEventRequest: {
            /** Event Id */
            event_id: number;
            /** Place After Event Id */
            place_after_event_id: number;
        };
        /** MoveScheduleEventResult */
        MoveScheduleEventResult: {
            event: components["schemas"]["ScheduleEventDTO"];
            place_after_event: components["schemas"]["ScheduleEventDTO"];
        };
        /** NominationVotingDTO */
        NominationVotingDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** User Vote Id */
            user_vote_id: number | null;
        };
        /** NominationWithParticipantsVotingDTO */
        NominationWithParticipantsVotingDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** User Vote Id */
            user_vote_id: number | null;
            /** Participants */
            participants: components["schemas"]["ParticipantVotingDTO"][];
        };
        /** Order */
        Order: {
            /** Id */
            id: string;
            status: components["schemas"]["OrderStatus"];
            /** Event */
            event: string;
            /** Tickets */
            tickets: components["schemas"]["Ticket"][];
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "executed" | "done" | "cancelled" | "expired" | "in_progress";
        /** ParticipantVotingDTO */
        ParticipantVotingDTO: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Voting Number */
            voting_number: number | null;
            /** Votes Count */
            votes_count: number;
            /** User Vote Id */
            user_vote_id: number | null;
        };
        /** RegisterUserRequest */
        RegisterUserRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** ScheduleChangeDTO */
        ScheduleChangeDTO: {
            /** Id */
            id: number;
            type: components["schemas"]["ScheduleChangeType"];
            /** Mailing Id */
            mailing_id: string | null;
            /** User Id */
            user_id: number | null;
            /** Send Global Announcement */
            send_global_announcement: boolean;
            changed_event: components["schemas"]["ScheduleChangeEventDTO"] | null;
            argument_event: components["schemas"]["ScheduleChangeEventDTO"] | null;
            user: components["schemas"]["ScheduleChangeUserDTO"] | null;
        };
        /** ScheduleChangeEventDTO */
        ScheduleChangeEventDTO: {
            /** Id */
            id: number;
            /** Public Id */
            public_id: number;
            /** Title */
            title: string;
        };
        /**
         * ScheduleChangeType
         * @enum {string}
         */
        ScheduleChangeType: "set_as_current" | "moved" | "skipped" | "unskipped";
        /** ScheduleChangeUserDTO */
        ScheduleChangeUserDTO: {
            /** Id */
            id: number;
            /** Username */
            username: string | null;
        };
        /** ScheduleEventDTO */
        ScheduleEventDTO: {
            /** Id */
            id: number;
            /** Public Id */
            public_id: number;
            /** Title */
            title: string;
            /** Duration */
            duration: number;
            /** Order */
            order: number;
            /** Is Current */
            is_current: boolean;
            /** Is Skipped */
            is_skipped: boolean;
            /** Nomination Title */
            nomination_title: string;
            /** Block Title */
            block_title: string;
            /** Queue */
            queue: number | null;
            /** Time Until */
            time_until: number | null;
            user_subscription: components["schemas"]["ScheduleEventSubscriptionDTO"] | null;
        };
        /** ScheduleEventSubscriptionDTO */
        ScheduleEventSubscriptionDTO: {
            /** Id */
            id: number;
            /** Counter */
            counter: number;
        };
        /** SetCurrentScheduleEventRequest */
        SetCurrentScheduleEventRequest: {
            /** Event Id */
            event_id: number | null;
        };
        /** SetCurrentScheduleEventResponse */
        SetCurrentScheduleEventResponse: {
            current_event: components["schemas"]["ScheduleEventDTO"] | null;
            /** Schedule Change Id */
            schedule_change_id: number;
        };
        /** SubscriptionDTO */
        SubscriptionDTO: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Counter */
            counter: number;
            event: components["schemas"]["SubscriptionEventDTO"];
        };
        /** SubscriptionEventDTO */
        SubscriptionEventDTO: {
            /** Id */
            id: number;
            /** Public Id */
            public_id: number;
            /** Title */
            title: string;
            /** Is Skipped */
            is_skipped: boolean;
            /** Order */
            order: number;
            /** Queue */
            queue: number | null;
            /** Cumulative Duration */
            cumulative_duration: number | null;
        };
        /** TCloudWebhookPayload */
        TCloudWebhookPayload: {
            data: components["schemas"]["Order"];
            /** Type */
            type: string;
        };
        /** Ticket */
        Ticket: {
            /** Id */
            id: string;
            /** Serial */
            serial: string;
            /** Number */
            number: number;
            /** Barcode */
            barcode: string | null;
            /** Status */
            status: string;
            /** Price */
            price: string;
            /** Nominal */
            nominal: string;
            /** Discount */
            discount: string;
            /** Extra */
            extra: string;
            /** Full */
            full: string;
            /** Set */
            set: string;
            /** Tariff */
            tariff: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UpdateScheduleEventSkipRequest */
        UpdateScheduleEventSkipRequest: {
            /** Event Id */
            event_id: number;
            /** Is Skipped */
            is_skipped: boolean;
        };
        /** UpdateScheduleEventSkipResult */
        UpdateScheduleEventSkipResult: {
            event: components["schemas"]["ScheduleEventDTO"];
        };
        /** UserPermissionDTO */
        UserPermissionDTO: {
            /** Name */
            name: string;
            /** Object Type */
            object_type: string | null;
            /** Object Id */
            object_id: number | null;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "visitor" | "participant" | "helper" | "org";
        /** UserSettings */
        UserSettings: {
            /**
             * Items Per Page
             * @default 4
             */
            items_per_page: number;
            /**
             * Receive All Announcements
             * @default true
             */
            receive_all_announcements: boolean;
        };
        /** UserTicketDTO */
        UserTicketDTO: {
            /** Id */
            id: number;
            /** Barcode */
            barcode: string;
            role: components["schemas"]["UserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VotingStatus
         * @enum {string}
         */
        VotingStatus: "open" | "not_authenticated" | "no_ticket" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullUserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_user_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullUserDTO"];
                };
            };
        };
    };
    stream_events_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_schedule_schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetScheduleResponse"];
                };
            };
        };
    };
    set_event_as_current_schedule_set_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCurrentScheduleEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetCurrentScheduleEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_schedule_event_schedule_move_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveScheduleEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveScheduleEventResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_schedule_event_skip_schedule_set_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleEventSkipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateScheduleEventSkipResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_changes_schedule_changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListScheduleChangesResponse"];
                };
            };
        };
    };
    undo_schedule_change_schedule_changes__schedule_change_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_change_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_subscription_schedule_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subscription_schedule_subscriptions__subscription_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subscription_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voting_status_voting_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVotingStateResponse"];
                };
            };
        };
    };
    list_voting_nominations_voting_nominations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListVotingNominationsResponse"];
                };
            };
        };
    };
    list_voting_nominations_voting_nominations__nomination_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nomination_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NominationWithParticipantsVotingDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_vote_voting_nominations__nomination_id__vote_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nomination_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddVoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddVoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_vote_voting_nominations__nomination_id__vote_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nomination_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_tcloud_order_webhooks_tcloud_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TCloudWebhookPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
