services:
  frontend:
    build:
      context: ./frontend
      target: prod
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - '3000:3000'
    restart: unless-stopped
    profiles: [ "core" ]

  api:
    build: ./backend
    depends_on:
      - migration
      - redis
      - nats
    volumes:
      - ./config:/run/config:ro
    env_file:
      - .env
    environment:
      DB__HOST: "db"
      REDIS__HOST: "redis"
      NATS__HOST: "nats"
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "8000"
      UVICORN_FORWARDED_ALLOW_IPS: "*"
    ports:
      - '8000:8000'
    restart: unless-stopped
    stop_signal: SIGINT
    profiles: [ "core" ]

  faststream:
    build: ./backend
    depends_on:
      - migration
      - nats
      - redis
    volumes:
      - ./config:/run/config:ro
    env_file:
      - .env
    command: [ "faststream", "run", "--factory", "fanfan.main.faststream:create_app" ]
    restart: unless-stopped
    profiles: [ "core" ]

  migration:
    build: ./backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/alembic.ini:/app/alembic.ini
    command: [ "alembic", "upgrade", "head" ]
    restart: on-failure
    profiles: [ "core" ]

  db:
    image: postgres:17-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB__USER}"
      POSTGRES_PASSWORD: "${DB__PASSWORD}"
      POSTGRES_DB: "${DB__NAME}"
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 60s
      retries: 10
      start_period: 5s
    profiles: [ "core" ]

  nats:
    image: docker.io/nats:alpine
    volumes:
      - nats-data:/data
    command: "--js --sd=/data --user ${NATS__USER} --pass ${NATS__PASSWORD}"
    ports:
      - "4222:4222"
    restart: unless-stopped
    profiles: [ "core" ]

  pgbackup:
    image: prodrigestivill/postgres-backup-local
    depends_on:
      - db
    volumes:
      - pgbackup-data:/backups
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB__NAME}
      - POSTGRES_USER=${DB__USER}
      - POSTGRES_PASSWORD=${DB__PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@every 6h00m00s
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    restart: unless-stopped
    profiles: [ "ops" ]

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS__PASSWORD}"
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$${REDIS__PASSWORD}\" ping | grep PONG" ]
      interval: 5s
      timeout: 20s
      retries: 5
    profiles: [ "core" ]

volumes:
  db-data: {}
  pgbackup-data: {}
  redis-data: {}
  nats-data: {}
