from typing import Protocol

from fanfan.application.dto.mailing import MailingDTO
from fanfan.application.dto.page import Pagination
from fanfan.core.models.mailing import Mailing
from fanfan.core.vo.mailing import MailingId, MailingStatus


class MailingGateway(Protocol):
    async def add(self, mailing: Mailing) -> None: ...
    async def get(self, mailing_id: MailingId) -> Mailing | None: ...

    async def set_status(
        self, mailing_id: MailingId, status: MailingStatus
    ) -> None: ...
    async def set_body(self, mailing_id: MailingId, body: str) -> None: ...
    async def set_total(self, mailing_id: MailingId, total_count: int) -> None: ...
    # Atomically increment sent_count; returns the post-increment
    # (sent_count, total_count) so the caller can decide completion.
    async def increment_sent(self, mailing_id: MailingId) -> tuple[int, int]: ...

    async def read_mailing(self, mailing_id: MailingId) -> MailingDTO | None: ...
    async def read_broadcasts(self, pagination: Pagination) -> list[MailingDTO]: ...
