from typing import Protocol

from fanfan.application.dto.schedule import ScheduleItemFullDTO
from fanfan.core.models.schedule_item import ScheduleItem
from fanfan.core.vo.schedule_item import ScheduleItemId


class ScheduleItemGateway(Protocol):
    async def add(self, event: ScheduleItem) -> None: ...
    async def get_by_id(
        self, schedule_item_id: ScheduleItemId
    ) -> ScheduleItem | None: ...
    async def get_by_queue(self, queue: int) -> ScheduleItem | None: ...
    async def get_current(self) -> ScheduleItem | None: ...
    async def get_next(self) -> ScheduleItem | None: ...
    async def list_all(self) -> list[ScheduleItem]: ...
    async def get_next_by_order(self, order: float) -> ScheduleItem | None: ...
    async def get_previous_by_order(self, order: float) -> ScheduleItem | None: ...
    async def save(self, event: ScheduleItem) -> None: ...
    async def delete(self, event: ScheduleItem) -> None: ...

    # Read projections (return DTOs, not aggregates)
    async def read_next_schedule_item(self) -> ScheduleItemFullDTO | None: ...

    async def read_current_schedule_item(self) -> ScheduleItemFullDTO | None: ...

    async def read_list_schedule(self) -> list[ScheduleItemFullDTO]: ...
