from typing import Protocol

from fanfan.core.models.ticket import Ticket
from fanfan.core.vo.user import UserId


class TicketGateway(Protocol):
    async def add(self, ticket: Ticket) -> None: ...
    async def add_generated(self, tickets: list[Ticket]) -> None: ...
    async def get_by_barcode(self, barcode: str) -> Ticket | None: ...
    async def get_by_ticketscloud_ticket_id(
        self, ticketscloud_ticket_id: str
    ) -> Ticket | None: ...
    async def get_by_user_id(self, user_id: UserId) -> Ticket | None: ...
    async def save(self, ticket: Ticket) -> None: ...
    async def delete(self, ticket: Ticket) -> None: ...
