from typing import Protocol

from fanfan.application.dto.page import Pagination
from fanfan.application.dto.user import (
    CurrentUserDTO,
    UserBaseDTO,
    UserDetailsDTO,
    UserListItemDTO,
)
from fanfan.core.models.user import User
from fanfan.core.vo.user import UserId, UserRole


class UserGateway(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UserId) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> None: ...

    async def read_current_user(self, user_id: UserId) -> CurrentUserDTO | None: ...

    async def read_all_by_roles(self, *roles: UserRole) -> list[UserBaseDTO]: ...

    # The prize-draw pool: users who have voted in every votable nomination.
    # Computed on request from the votes table (see the SQL adapter), so a draw
    # always reflects who is eligible right now.
    async def count_voting_contest_pool(self) -> int: ...

    async def read_random_voting_contest_entrant(self) -> UserBaseDTO | None: ...

    async def read_all_by_receive_all_announcements(self) -> list[UserBaseDTO]: ...

    async def read_schedule_editors(self) -> list[UserBaseDTO]: ...

    # `search` filters by a case-insensitive substring of username or email;
    # None (or blank) returns everyone. count_users applies the same filter so
    # the two agree for pagination.
    async def read_users_page(
        self, *, pagination: Pagination, search: str | None
    ) -> list[UserListItemDTO]: ...

    async def count_users(self, *, search: str | None) -> int: ...

    async def read_user_details(self, user_id: UserId) -> UserDetailsDTO | None: ...
