from typing import Protocol

from fanfan.application.dto.user import CurrentUserDTO, UserBaseDTO
from fanfan.core.models.user import User
from fanfan.core.vo.user import UserId, UserRole


class UserGateway(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UserId) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> None: ...

    async def read_current_user(self, user_id: UserId) -> CurrentUserDTO | None: ...

    async def read_all_by_roles(self, *roles: UserRole) -> list[UserBaseDTO]: ...

    async def read_all_by_receive_all_announcements(self) -> list[UserBaseDTO]: ...

    async def read_schedule_editors(self) -> list[UserBaseDTO]: ...
