"""init

Revision ID: 001
Revises:
Create Date: 2026-03-04 20:57:19.211820

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE schedule_order_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "SET_AS_CURRENT", "MOVED", "SKIPPED", "UNSKIPPED", name="schedulechangetype"
    ).create(op.get_bind())
    sa.Enum("VISITOR", "PARTICIPANT", "HELPER", "ORG", name="userrole").create(
        op.get_bind()
    )
    sa.Enum(
        "DEFAULT",
        "SCHEDULE_CHANGE",
        "SCHEDULE_SUBSCRIPTION",
        "MESSAGE",
        "POINTS_RECEIVED",
        name="notificationtype",
    ).create(op.get_bind())
    sa.Enum(
        "TEXT",
        "PHONE",
        "TEXTAREA",
        "LINK",
        "CHECKBOX",
        "USER",
        "DURATION",
        "IMAGE",
        "SELECT",
        "NUM",
        "FILE",
        name="valuetype",
    ).create(op.get_bind())
    sa.Enum("PENDING", "FINISHED", "CANCELLED", name="mailingstatus").create(
        op.get_bind()
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), server_default="1", nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "nominations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cosplay2_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_votable", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nominations")),
        sa.UniqueConstraint("code", name=op.f("uq_nominations_code")),
        sa.UniqueConstraint("title", name=op.f("uq_nominations_title")),
    )
    op.create_index(
        op.f("ix_nominations_cosplay2_id"), "nominations", ["cosplay2_id"], unique=True
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("name", name=op.f("uq_permissions_name")),
    )
    op.create_table(
        "schedule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("public_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("is_skipped", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("nomination_title", sa.String(), nullable=True),
        sa.Column("block_title", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "order",
            sa.Float(),
            server_default=sa.text("nextval('schedule_order_seq')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule")),
        sa.UniqueConstraint("order", name=op.f("uq_schedule_order")),
        sa.UniqueConstraint("public_id", name=op.f("uq_schedule_public_id")),
    )
    op.create_index(
        "ix_only_one_current",
        "schedule",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("is_current IS true"),
    )
    op.create_index(op.f("ix_schedule_title"), "schedule", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column(
            "role",
            postgresql.ENUM(
                "VISITOR",
                "PARTICIPANT",
                "HELPER",
                "ORG",
                name="userrole",
                create_type=False,
            ),
            server_default="VISITOR",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "mailings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "FINISHED",
                "CANCELLED",
                name="mailingstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("by_user_id", sa.Uuid(), nullable=True),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["by_user_id"],
            ["users.id"],
            name=op.f("fk_mailings_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailings")),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cosplay2_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("voting_number", sa.Integer(), nullable=True),
        sa.Column("nomination_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["nomination_id"],
            ["nominations.id"],
            name=op.f("fk_participants_nomination_id_nominations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
        sa.UniqueConstraint(
            "nomination_id", "voting_number", name=op.f("uq_participants_nomination_id")
        ),
    )
    op.create_index(
        op.f("ix_participants_cosplay2_id"),
        "participants",
        ["cosplay2_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_participants_title"), "participants", ["title"], unique=False
    )
    op.create_table(
        "push_subs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("p256dh", sa.String(), nullable=False),
        sa.Column("auth", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_subs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subs")),
        sa.UniqueConstraint("endpoint", name=op.f("uq_push_subs_endpoint")),
    )
    op.create_table(
        "social_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_social_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
        sa.UniqueConstraint(
            "provider", "provider_id", name=op.f("uq_social_accounts_provider")
        ),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["schedule.id"],
            name=op.f("fk_subscriptions_event_id_schedule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "event_id", "user_id", name=op.f("uq_subscriptions_event_id")
        ),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("barcode", sa.String(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "VISITOR",
                "PARTICIPANT",
                "HELPER",
                "ORG",
                name="userrole",
                create_type=False,
            ),
            server_default="VISITOR",
            nullable=False,
        ),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("used_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("ticketscloud_ticket_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_tickets_issued_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["users.id"],
            name=op.f("fk_tickets_used_by_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
        sa.UniqueConstraint("barcode", name=op.f("uq_tickets_barcode")),
        sa.UniqueConstraint(
            "ticketscloud_ticket_id", name=op.f("uq_tickets_ticketscloud_ticket_id")
        ),
        sa.UniqueConstraint("used_by_user_id", name=op.f("uq_tickets_used_by_user_id")),
    )
    op.create_table(
        "user_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_flags_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_flags")),
    )
    op.create_table(
        "user_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=True),
        sa.Column("object_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_user_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_permissions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_permissions")),
        sa.UniqueConstraint(
            "user_id",
            "permission_id",
            "object_id",
            "object_type",
            name=op.f("uq_user_permissions_user_id"),
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "DEFAULT",
                "SCHEDULE_CHANGE",
                "SCHEDULE_SUBSCRIPTION",
                "MESSAGE",
                "POINTS_RECEIVED",
                name="notificationtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("mailing_id", sa.Uuid(), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mailing_id"],
            ["mailings.id"],
            name=op.f("fk_notifications_mailing_id_mailings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "participant_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "TEXT",
                "PHONE",
                "TEXTAREA",
                "LINK",
                "CHECKBOX",
                "USER",
                "DURATION",
                "IMAGE",
                "SELECT",
                "NUM",
                "FILE",
                name="valuetype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_participant_values_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant_values")),
    )
    op.create_table(
        "schedule_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "SET_AS_CURRENT",
                "MOVED",
                "SKIPPED",
                "UNSKIPPED",
                name="schedulechangetype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("changed_event_id", sa.Uuid(), nullable=True),
        sa.Column("argument_event_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("send_global_announcement", sa.Boolean(), nullable=False),
        sa.Column("mailing_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["argument_event_id"],
            ["schedule.id"],
            name=op.f("fk_schedule_changes_argument_event_id_schedule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_event_id"],
            ["schedule.id"],
            name=op.f("fk_schedule_changes_changed_event_id_schedule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mailing_id"],
            ["mailings.id"],
            name=op.f("fk_schedule_changes_mailing_id_mailings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_schedule_changes_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_changes")),
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("participant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_votes_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_votes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_votes")),
        sa.UniqueConstraint("user_id", "participant_id", name=op.f("uq_votes_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("votes")
    op.drop_table("schedule_changes")
    op.drop_table("participant_values")
    op.drop_table("notifications")
    op.drop_table("user_permissions")
    op.drop_table("user_flags")
    op.drop_table("tickets")
    op.drop_table("subscriptions")
    op.drop_table("social_accounts")
    op.drop_table("push_subs")
    op.drop_index(op.f("ix_participants_title"), table_name="participants")
    op.drop_index(op.f("ix_participants_cosplay2_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_table("mailings")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_schedule_title"), table_name="schedule")
    op.drop_index(
        "ix_only_one_current",
        table_name="schedule",
        postgresql_where=sa.text("is_current IS true"),
    )
    op.drop_table("schedule")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_nominations_cosplay2_id"), table_name="nominations")
    op.drop_table("nominations")
    op.drop_table("app_settings")
    sa.Enum("PENDING", "FINISHED", "CANCELLED", name="mailingstatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "TEXT",
        "PHONE",
        "TEXTAREA",
        "LINK",
        "CHECKBOX",
        "USER",
        "DURATION",
        "IMAGE",
        "SELECT",
        "NUM",
        "FILE",
        name="valuetype",
    ).drop(op.get_bind())
    sa.Enum(
        "DEFAULT",
        "SCHEDULE_CHANGE",
        "SCHEDULE_SUBSCRIPTION",
        "MESSAGE",
        "POINTS_RECEIVED",
        name="notificationtype",
    ).drop(op.get_bind())
    sa.Enum("VISITOR", "PARTICIPANT", "HELPER", "ORG", name="userrole").drop(
        op.get_bind()
    )
    sa.Enum(
        "SET_AS_CURRENT", "MOVED", "SKIPPED", "UNSKIPPED", name="schedulechangetype"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE schedule_order_seq")
