"""notifications_in_db

Revision ID: 004
Revises: 003
Create Date: 2026-02-27 18:05:28.208984

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mailings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["by_user_id"],
            ["users.id"],
            name=op.f("fk_mailings_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailings")),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("mailing_id", sa.Uuid(), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mailing_id"],
            ["mailings.id"],
            name=op.f("fk_notifications_mailing_id_mailings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.alter_column(
        "schedule_changes",
        "mailing_id",
        existing_type=sa.VARCHAR(),
        type_=postgresql.UUID(),
        postgresql_using="mailing_id::uuid",
    )
    op.create_foreign_key(
        op.f("fk_schedule_changes_mailing_id_mailings"),
        "schedule_changes",
        "mailings",
        ["mailing_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedule_changes_mailing_id_mailings"),
        "schedule_changes",
        type_="foreignkey",
    )
    op.alter_column(
        "schedule_changes",
        "mailing_id",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_table("notifications")
    op.drop_table("mailings")
    # ### end Alembic commands ###
