"""new_notification_type_broadcast

Revision ID: 005
Revises: 004
Create Date: 2026-05-09 16:24:27.624658

"""

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "005"
down_revision = "004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # ty:ignore[unresolved-attribute]
        enum_schema="public",
        enum_name="notificationtype",
        new_values=[
            "DEFAULT",
            "SCHEDULE_CHANGE",
            "SCHEDULE_SUBSCRIPTION",
            "MESSAGE",
            "POINTS_RECEIVED",
            "BROADCAST",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="notifications", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # ty:ignore[unresolved-attribute]
        enum_schema="public",
        enum_name="notificationtype",
        new_values=[
            "DEFAULT",
            "SCHEDULE_CHANGE",
            "SCHEDULE_SUBSCRIPTION",
            "MESSAGE",
            "POINTS_RECEIVED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="notifications", column_name="type"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
