"""next_event_changed

Revision ID: 006
Revises: 005
Create Date: 2026-06-04 19:39:04.837475

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule_changes",
        "send_global_announcement",
        new_column_name="next_event_changed",
        existing_type=sa.Boolean(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "schedule_changes",
        "next_event_changed",
        new_column_name="send_global_announcement",
        existing_type=sa.Boolean(),
    )
    # ### end Alembic commands ###
