"""social_ids

Revision ID: 006
Revises: 005
Create Date: 2026-03-01 14:34:36.940341

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_ids",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_social_ids_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_ids")),
        sa.UniqueConstraint(
            "provider", "provider_id", name=op.f("uq_social_ids_provider")
        ),
    )
    op.drop_constraint(op.f("uq_users_tg_id"), "users", type_="unique")
    op.drop_column("users", "tg_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("tg_id", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_users_tg_id"), "users", ["tg_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_table("social_ids")
    # ### end Alembic commands ###
