"""add_fk_indexes

Revision ID: 008
Revises: 007
Create Date: 2026-06-07 15:56:16.737312

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "008"
down_revision = "007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_notifications_mailing_id"),
        "notifications",
        ["mailing_id"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_user_id_created_at",
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_participant_values_participant_id"),
        "participant_values",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_push_subs_user_id"), "push_subs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_changes_argument_event_id"),
        "schedule_changes",
        ["argument_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_changes_changed_event_id"),
        "schedule_changes",
        ["changed_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_changes_mailing_id"),
        "schedule_changes",
        ["mailing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_changes_user_id"),
        "schedule_changes",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_social_accounts_user_id"), "social_accounts", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_flags_user_id"), "user_flags", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_votes_participant_id"), "votes", ["participant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_votes_participant_id"), table_name="votes")
    op.drop_index(op.f("ix_user_flags_user_id"), table_name="user_flags")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_social_accounts_user_id"), table_name="social_accounts")
    op.drop_index(op.f("ix_schedule_changes_user_id"), table_name="schedule_changes")
    op.drop_index(op.f("ix_schedule_changes_mailing_id"), table_name="schedule_changes")
    op.drop_index(
        op.f("ix_schedule_changes_changed_event_id"), table_name="schedule_changes"
    )
    op.drop_index(
        op.f("ix_schedule_changes_argument_event_id"), table_name="schedule_changes"
    )
    op.drop_index(op.f("ix_push_subs_user_id"), table_name="push_subs")
    op.drop_index(
        op.f("ix_participant_values_participant_id"), table_name="participant_values"
    )
    op.drop_index("ix_notifications_user_id_created_at", table_name="notifications")
    op.drop_index(op.f("ix_notifications_mailing_id"), table_name="notifications")
    op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
    # ### end Alembic commands ###
