"""009_schema_review_fixes

Revision ID: 009
Revises: 008
Create Date: 2026-06-10 21:25:30.999566

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "009"
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_mailings_by_user_id"), "mailings", ["by_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_issued_by_user_id"),
        "tickets",
        ["issued_by_user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_user_flags_user_id"), table_name="user_flags")
    op.create_unique_constraint(
        op.f("uq_user_flags_user_id"), "user_flags", ["user_id", "name"]
    )
    op.drop_constraint(
        op.f("uq_user_permissions_user_id"), "user_permissions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_user_permissions_user_id"),
        "user_permissions",
        ["user_id", "permission_id", "object_id", "object_type"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("ix_user_permissions_permission_id"),
        "user_permissions",
        ["permission_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Alembic does not diff deferrable/initially flags, so this is hand-written.
    # Recreate uq_schedule_order as DEFERRABLE INITIALLY DEFERRED so a single
    # transaction can swap two events' order values without tripping the
    # unique constraint on an intermediate flush.
    op.drop_constraint(op.f("uq_schedule_order"), "schedule", type_="unique")
    op.create_unique_constraint(
        op.f("uq_schedule_order"),
        "schedule",
        ["order"],
        deferrable=True,
        initially="DEFERRED",
    )


def downgrade() -> None:
    # Revert uq_schedule_order back to a plain (non-deferrable) unique.
    op.drop_constraint(op.f("uq_schedule_order"), "schedule", type_="unique")
    op.create_unique_constraint(op.f("uq_schedule_order"), "schedule", ["order"])

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_permissions_permission_id"), table_name="user_permissions"
    )
    op.drop_constraint(
        op.f("uq_user_permissions_user_id"), "user_permissions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_user_permissions_user_id"),
        "user_permissions",
        ["user_id", "permission_id", "object_id", "object_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("uq_user_flags_user_id"), "user_flags", type_="unique")
    op.create_index(
        op.f("ix_user_flags_user_id"), "user_flags", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_tickets_issued_by_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_mailings_by_user_id"), table_name="mailings")
    # ### end Alembic commands ###
