"""mailing_status_sending_failed

Revision ID: 013
Revises: 012
Create Date: 2026-06-12 00:00:00.000000

"""

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "013"
down_revision = "012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # ty:ignore[unresolved-attribute]
        enum_schema="public",
        enum_name="mailingstatus",
        new_values=[
            "PENDING",
            "SENDING",
            "FINISHED",
            "CANCELLED",
            "FAILED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="mailings", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # ty:ignore[unresolved-attribute]
        enum_schema="public",
        enum_name="mailingstatus",
        new_values=[
            "PENDING",
            "FINISHED",
            "CANCELLED",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="mailings", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
