"""add_mailing_body_and_roles

Revision ID: b88de994c3b1
Revises: b8575c07d24a
Create Date: 2026-09-09 04:46:31.158213

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b88de994c3b1"
down_revision = "b8575c07d24a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Purely additive, nullable columns — safe against the deployed table with no
    # backfill. Mailings created before this migration never captured their text
    # or target roles, so NULL is the correct (and unrecoverable) value for them;
    # it is also the permanent value for schedule-change mailings, which are not
    # role-targeted.
    op.add_column("mailings", sa.Column("body", sa.String(), nullable=True))
    op.add_column(
        "mailings",
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mailings", "roles")
    op.drop_column("mailings", "body")
    # ### end Alembic commands ###
