"""social_identity_provider_user_id_not_null

Revision ID: b691d03eeef6
Revises: e3a7c1b5d902
Create Date: 2026-08-04 22:49:12.257806

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b691d03eeef6"
down_revision = "e3a7c1b5d902"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "social_identities",
        "provider_user_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "social_identities",
        "provider_user_id",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###
