"""add telegram_message_id to notifications

Revision ID: 2a22914f588f
Revises: 50bc789635be
Create Date: 2026-06-22 09:35:06.988031

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a22914f588f"
down_revision = "50bc789635be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications", "telegram_message_id")
    # ### end Alembic commands ###
