// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type ClientMeta,
	formDataBodySerializer,
	type Options as Options2,
	type RequestResult,
	type ServerSentEventsResult,
	type TDataShape,
	urlSearchParamsBodySerializer
} from './client';
import { client } from './client.gen';
import type {
	AddVoteData,
	AddVoteErrors,
	AddVoteResponses,
	CancelMailingData,
	CancelMailingErrors,
	CancelMailingResponses,
	CancelVoteData,
	CancelVoteErrors,
	CancelVoteResponses,
	ChangeCurrentUserEmailData,
	ChangeCurrentUserEmailErrors,
	ChangeCurrentUserEmailResponses,
	ChangeCurrentUserPasswordData,
	ChangeCurrentUserPasswordErrors,
	ChangeCurrentUserPasswordResponses,
	CheckSubscriptionData,
	CheckSubscriptionErrors,
	CheckSubscriptionResponses,
	ConfirmEmailCodeData,
	ConfirmEmailCodeErrors,
	ConfirmEmailCodeResponses,
	CountOnlineUsersData,
	CountOnlineUsersErrors,
	CountOnlineUsersResponses,
	CountUnreadNotificationsData,
	CountUnreadNotificationsErrors,
	CountUnreadNotificationsResponses,
	DebugData,
	DebugErrors,
	DebugResponses,
	DeleteSubscriptionData,
	DeleteSubscriptionErrors,
	DeleteSubscriptionResponses,
	DrawVotingContestWinnerData,
	DrawVotingContestWinnerErrors,
	DrawVotingContestWinnerResponses,
	GenerateTicketsData,
	GenerateTicketsErrors,
	GenerateTicketsResponses,
	GetCurrentUserData,
	GetCurrentUserErrors,
	GetCurrentUserResponses,
	GetPublicConfigData,
	GetPublicConfigErrors,
	GetPublicConfigResponses,
	GetScheduleData,
	GetScheduleErrors,
	GetScheduleResponses,
	GetSettingsData,
	GetSettingsErrors,
	GetSettingsResponses,
	GetSubscriptionsData,
	GetSubscriptionsErrors,
	GetSubscriptionsResponses,
	GetSyncSourcesData,
	GetSyncSourcesErrors,
	GetSyncSourcesResponses,
	GetUserData,
	GetUserErrors,
	GetUserResponses,
	GetVotingDashboardData,
	GetVotingDashboardErrors,
	GetVotingDashboardResponses,
	GetVotingNominationData,
	GetVotingNominationErrors,
	GetVotingNominationResponses,
	GetVotingStatusData,
	GetVotingStatusErrors,
	GetVotingStatusResponses,
	HealthCheckData,
	HealthCheckErrors,
	HealthCheckResponses,
	ImportScheduleData,
	ImportScheduleErrors,
	ImportScheduleResponses,
	LinkTicketData,
	LinkTicketErrors,
	LinkTicketResponses,
	ListBroadcastsData,
	ListBroadcastsErrors,
	ListBroadcastsResponses,
	ListFeedbackData,
	ListFeedbackErrors,
	ListFeedbackResponses,
	ListOauthProvidersData,
	ListOauthProvidersErrors,
	ListOauthProvidersResponses,
	ListScheduleChangesData,
	ListScheduleChangesErrors,
	ListScheduleChangesResponses,
	ListUserNotificationsData,
	ListUserNotificationsErrors,
	ListUserNotificationsResponses,
	ListUsersData,
	ListUsersErrors,
	ListUsersResponses,
	ListVotingNominationsData,
	ListVotingNominationsErrors,
	ListVotingNominationsResponses,
	LoginData,
	LoginErrors,
	LoginResponses,
	LoginWithCodeData,
	LoginWithCodeErrors,
	LoginWithCodeResponses,
	LogoutUserData,
	LogoutUserErrors,
	LogoutUserResponses,
	MarkAllNotificationsReadData,
	MarkAllNotificationsReadErrors,
	MarkAllNotificationsReadResponses,
	MarkNotificationsReadData,
	MarkNotificationsReadErrors,
	MarkNotificationsReadResponses,
	MoveScheduleEventData,
	MoveScheduleEventErrors,
	MoveScheduleEventResponses,
	NewSubscriptionData,
	NewSubscriptionErrors,
	NewSubscriptionResponses,
	OauthCallbackData,
	OauthCallbackErrors,
	OauthCallbackResponses,
	ProcessTcloudOrderData,
	ProcessTcloudOrderErrors,
	ProcessTcloudOrderResponses,
	RequestLoginCodeData,
	RequestLoginCodeErrors,
	RequestLoginCodeResponses,
	RequestSyncData,
	RequestSyncErrors,
	RequestSyncResponses,
	SendBroadcastData,
	SendBroadcastErrors,
	SendBroadcastResponses,
	SendTestNotificationData,
	SendTestNotificationErrors,
	SendTestNotificationResponses,
	SetEventAsCurrentData,
	SetEventAsCurrentErrors,
	SetEventAsCurrentResponses,
	SetVotingTimeRangeData,
	SetVotingTimeRangeErrors,
	SetVotingTimeRangeResponses,
	StartAccountLinkData,
	StartAccountLinkErrors,
	StartAccountLinkResponses,
	StartSocialLoginData,
	StartSocialLoginErrors,
	StartSocialLoginResponses,
	StreamEventsData,
	StreamEventsErrors,
	StreamEventsResponses,
	SubmitFeedbackData,
	SubmitFeedbackErrors,
	SubmitFeedbackResponses,
	SubscribeData,
	SubscribeErrors,
	SubscribeResponses,
	UncheckCurrentEventData,
	UncheckCurrentEventErrors,
	UncheckCurrentEventResponses,
	UndoScheduleChangeData,
	UndoScheduleChangeErrors,
	UndoScheduleChangeResponses,
	UnlinkTelegramAccountData,
	UnlinkTelegramAccountErrors,
	UnlinkTelegramAccountResponses,
	UnlinkVkAccountData,
	UnlinkVkAccountErrors,
	UnlinkVkAccountResponses,
	UnsubscribeData,
	UnsubscribeErrors,
	UnsubscribeResponses,
	UpdateCurrentUserData,
	UpdateCurrentUserErrors,
	UpdateCurrentUserResponses,
	UpdateCurrentUserSettingsData,
	UpdateCurrentUserSettingsErrors,
	UpdateCurrentUserSettingsResponses,
	UpdateScheduleEventData,
	UpdateScheduleEventErrors,
	UpdateScheduleEventResponses,
	UpdateSettingsData,
	UpdateSettingsErrors,
	UpdateSettingsResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Debug
 */
export const debug = <ThrowOnError extends boolean = false>(
	options?: Options<DebugData, ThrowOnError>
): RequestResult<DebugResponses, DebugErrors, ThrowOnError> =>
	(options?.client ?? client).get<DebugResponses, DebugErrors, ThrowOnError>({
		url: '/debug/',
		...options
	});

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
	options?: Options<HealthCheckData, ThrowOnError>
): RequestResult<HealthCheckResponses, HealthCheckErrors, ThrowOnError> =>
	(options?.client ?? client).get<HealthCheckResponses, HealthCheckErrors, ThrowOnError>({
		url: '/debug/health',
		...options
	});

/**
 * Login and create session
 *
 * Authenticates user with email and password. Sets an HttpOnly cookie with a Redis-backed session id.
 */
export const login = <ThrowOnError extends boolean = false>(
	options: Options<LoginData, ThrowOnError>
): RequestResult<LoginResponses, LoginErrors, ThrowOnError> =>
	(options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
		...urlSearchParamsBodySerializer,
		url: '/auth/login',
		...options,
		headers: {
			'Content-Type': 'application/x-www-form-urlencoded',
			...options.headers
		}
	});

/**
 * Confirm user email with code
 *
 * Confirms the new email address using a one-time code received at that address.
 */
export const confirmEmailCode = <ThrowOnError extends boolean = false>(
	options: Options<ConfirmEmailCodeData, ThrowOnError>
): RequestResult<ConfirmEmailCodeResponses, ConfirmEmailCodeErrors, ThrowOnError> =>
	(options.client ?? client).post<ConfirmEmailCodeResponses, ConfirmEmailCodeErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/auth/confirm-email-code',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Request email login code
 *
 * Sends a one-time six-digit sign-in code to the requested email address. Creates an account automatically when the email is new. The code is sent before the response returns, so a delivery failure is reported instead of being swallowed.
 */
export const requestLoginCode = <ThrowOnError extends boolean = false>(
	options: Options<RequestLoginCodeData, ThrowOnError>
): RequestResult<RequestLoginCodeResponses, RequestLoginCodeErrors, ThrowOnError> =>
	(options.client ?? client).post<RequestLoginCodeResponses, RequestLoginCodeErrors, ThrowOnError>({
		url: '/auth/request-login-code',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Login with email code
 *
 * Consumes a one-time email code and sets session cookie.
 */
export const loginWithCode = <ThrowOnError extends boolean = false>(
	options: Options<LoginWithCodeData, ThrowOnError>
): RequestResult<LoginWithCodeResponses, LoginWithCodeErrors, ThrowOnError> =>
	(options.client ?? client).post<LoginWithCodeResponses, LoginWithCodeErrors, ThrowOnError>({
		url: '/auth/login-with-code',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Logout user
 *
 * Clears session cookie and removes Redis session state.
 */
export const logoutUser = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutUserData, ThrowOnError>
): RequestResult<LogoutUserResponses, LogoutUserErrors, ThrowOnError> =>
	(options?.client ?? client).post<LogoutUserResponses, LogoutUserErrors, ThrowOnError>({
		url: '/auth/logout',
		...options
	});

/**
 * List enabled social login providers
 *
 * Returns the social login providers this deployment offers, in display order. The login screen renders one button per provider; a provider missing here is disabled and its start endpoint is rejected. Unauthenticated on purpose — it only reveals which buttons to draw, which is not sensitive.
 */
export const listOauthProviders = <ThrowOnError extends boolean = false>(
	options?: Options<ListOauthProvidersData, ThrowOnError>
): RequestResult<ListOauthProvidersResponses, ListOauthProvidersErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListOauthProvidersResponses,
		ListOauthProvidersErrors,
		ThrowOnError
	>({ url: '/auth/oauth/providers', ...options });

/**
 * Start social login
 *
 * Redirects the browser to the provider's OAuth page to begin signing in. The provider then calls back to the callback endpoint to finish. If the redirect cannot be built the browser goes back to the login page with an `oauthLoginError` query param instead.
 */
export const startSocialLogin = <ThrowOnError extends boolean = false>(
	options: Options<StartSocialLoginData, ThrowOnError>
): RequestResult<StartSocialLoginResponses, StartSocialLoginErrors, ThrowOnError> =>
	(options.client ?? client).get<StartSocialLoginResponses, StartSocialLoginErrors, ThrowOnError>({
		url: '/auth/oauth/{provider}/start',
		...options
	});

/**
 * Finish a social login or account link
 *
 * OAuth callback shared by both flows; which one it is comes from the intent stored in the OAuth state, never from the request. On a login it sets the session cookie and redirects to the app root; on a link it attaches the account and redirects to the profile page. Every failure also redirects, carrying an `oauthLoginError` or `oauthLinkError` query param the frontend turns into a toast; this route never answers with an error body, because the browser would render it as the page. Invoked by the provider, not called directly by the frontend.
 */
export const oauthCallback = <ThrowOnError extends boolean = false>(
	options: Options<OauthCallbackData, ThrowOnError>
): RequestResult<OauthCallbackResponses, OauthCallbackErrors, ThrowOnError> =>
	(options.client ?? client).get<OauthCallbackResponses, OauthCallbackErrors, ThrowOnError>({
		url: '/auth/oauth/{provider}/callback',
		...options
	});

/**
 * Get public config
 *
 * Returns the public festival config the SPA needs before login.
 */
export const getPublicConfig = <ThrowOnError extends boolean = false>(
	options?: Options<GetPublicConfigData, ThrowOnError>
): RequestResult<GetPublicConfigResponses, GetPublicConfigErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetPublicConfigResponses, GetPublicConfigErrors, ThrowOnError>({
		url: '/config',
		...options
	});

/**
 * Get current user
 *
 * Retrieves the currently authenticated user's profile information.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
	options?: Options<GetCurrentUserData, ThrowOnError>
): RequestResult<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/',
		...options
	});

/**
 * Update current user
 *
 * Updates the currently authenticated user's profile information.
 */
export const updateCurrentUser = <ThrowOnError extends boolean = false>(
	options: Options<UpdateCurrentUserData, ThrowOnError>
): RequestResult<UpdateCurrentUserResponses, UpdateCurrentUserErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		UpdateCurrentUserResponses,
		UpdateCurrentUserErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Update current user settings
 *
 * Updates the currently authenticated user's profile settings.
 */
export const updateCurrentUserSettings = <ThrowOnError extends boolean = false>(
	options: Options<UpdateCurrentUserSettingsData, ThrowOnError>
): RequestResult<
	UpdateCurrentUserSettingsResponses,
	UpdateCurrentUserSettingsErrors,
	ThrowOnError
> =>
	(options.client ?? client).patch<
		UpdateCurrentUserSettingsResponses,
		UpdateCurrentUserSettingsErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/settings',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Change current user password
 *
 * Changes the authenticated user's password. Requires the current password for verification when one is already set.
 */
export const changeCurrentUserPassword = <ThrowOnError extends boolean = false>(
	options: Options<ChangeCurrentUserPasswordData, ThrowOnError>
): RequestResult<
	ChangeCurrentUserPasswordResponses,
	ChangeCurrentUserPasswordErrors,
	ThrowOnError
> =>
	(options.client ?? client).post<
		ChangeCurrentUserPasswordResponses,
		ChangeCurrentUserPasswordErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/password',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Change current user email
 *
 * Sends a confirmation code to the new address. The stored email changes only once that code is confirmed. The code is sent before the response returns, so a delivery failure is reported instead of swallowed.
 */
export const changeCurrentUserEmail = <ThrowOnError extends boolean = false>(
	options: Options<ChangeCurrentUserEmailData, ThrowOnError>
): RequestResult<ChangeCurrentUserEmailResponses, ChangeCurrentUserEmailErrors, ThrowOnError> =>
	(options.client ?? client).post<
		ChangeCurrentUserEmailResponses,
		ChangeCurrentUserEmailErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/email',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Start account linking
 *
 * Redirects the browser to the provider's OAuth page to begin linking the account to the current user. The provider then calls back to the shared callback (`/auth/oauth/{provider}/callback`) to finish. If the redirect cannot be built the browser goes back to the profile page with an `oauthLinkError` query param instead.
 */
export const startAccountLink = <ThrowOnError extends boolean = false>(
	options: Options<StartAccountLinkData, ThrowOnError>
): RequestResult<StartAccountLinkResponses, StartAccountLinkErrors, ThrowOnError> =>
	(options.client ?? client).get<StartAccountLinkResponses, StartAccountLinkErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/connections/{provider}',
		...options
	});

/**
 * Unlink Telegram account
 *
 * Unlinks the Telegram account from the currently authenticated user.
 */
export const unlinkTelegramAccount = <ThrowOnError extends boolean = false>(
	options?: Options<UnlinkTelegramAccountData, ThrowOnError>
): RequestResult<UnlinkTelegramAccountResponses, UnlinkTelegramAccountErrors, ThrowOnError> =>
	(options?.client ?? client).delete<
		UnlinkTelegramAccountResponses,
		UnlinkTelegramAccountErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/connections/telegram',
		...options
	});

/**
 * Unlink VK account
 *
 * Unlinks the VK account from the currently authenticated user.
 */
export const unlinkVkAccount = <ThrowOnError extends boolean = false>(
	options?: Options<UnlinkVkAccountData, ThrowOnError>
): RequestResult<UnlinkVkAccountResponses, UnlinkVkAccountErrors, ThrowOnError> =>
	(options?.client ?? client).delete<UnlinkVkAccountResponses, UnlinkVkAccountErrors, ThrowOnError>(
		{
			security: [
				{
					in: 'cookie',
					name: 'session_id',
					type: 'apiKey'
				}
			],
			url: '/me/connections/vk',
			...options
		}
	);

/**
 * Link ticket
 *
 * Links provided ticket to current user.
 */
export const linkTicket = <ThrowOnError extends boolean = false>(
	options: Options<LinkTicketData, ThrowOnError>
): RequestResult<LinkTicketResponses, LinkTicketErrors, ThrowOnError> =>
	(options.client ?? client).post<LinkTicketResponses, LinkTicketErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/me/ticket',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Get festival settings
 *
 * Returns the current festival settings that organizers can manage.
 */
export const getSettings = <ThrowOnError extends boolean = false>(
	options?: Options<GetSettingsData, ThrowOnError>
): RequestResult<GetSettingsResponses, GetSettingsErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/settings',
		...options
	});

/**
 * Update festival settings
 *
 * Updates festival settings that are available to organizers.
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
	options: Options<UpdateSettingsData, ThrowOnError>
): RequestResult<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError> =>
	(options.client ?? client).patch<UpdateSettingsResponses, UpdateSettingsErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/settings',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Stream events via SSE
 *
 * Opens a Server-Sent Events connection to receive real-time event updates.
 */
export const streamEvents = <ThrowOnError extends boolean = false>(
	options?: Options<StreamEventsData, ThrowOnError, unknown>
): Promise<ServerSentEventsResult<StreamEventsResponses>> =>
	(options?.client ?? client).sse.get<StreamEventsResponses, StreamEventsErrors, ThrowOnError>({
		url: '/events',
		...options
	});

/**
 * Get current schedule
 *
 * Retrieves the full schedule using the GetSchedule interactor.
 */
export const getSchedule = <ThrowOnError extends boolean = false>(
	options?: Options<GetScheduleData, ThrowOnError>
): RequestResult<GetScheduleResponses, GetScheduleErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetScheduleResponses, GetScheduleErrors, ThrowOnError>({
		url: '/schedule/',
		...options
	});

/**
 * Set specific event as current
 *
 * Updates the schedule state to mark a specific event as active. Validates timing and event status.
 */
export const setEventAsCurrent = <ThrowOnError extends boolean = false>(
	options: Options<SetEventAsCurrentData, ThrowOnError>
): RequestResult<SetEventAsCurrentResponses, SetEventAsCurrentErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		SetEventAsCurrentResponses,
		SetEventAsCurrentErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/{event_id}/current',
		...options
	});

/**
 * Unset current schedule event
 *
 * Clears the currently active event from the schedule. Subject to rate limiting.
 */
export const uncheckCurrentEvent = <ThrowOnError extends boolean = false>(
	options?: Options<UncheckCurrentEventData, ThrowOnError>
): RequestResult<UncheckCurrentEventResponses, UncheckCurrentEventErrors, ThrowOnError> =>
	(options?.client ?? client).delete<
		UncheckCurrentEventResponses,
		UncheckCurrentEventErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/current',
		...options
	});

/**
 * Reorder schedule event
 *
 * Moves an event to a new position in the sequence, specifically after the provided event ID.
 */
export const moveScheduleEvent = <ThrowOnError extends boolean = false>(
	options: Options<MoveScheduleEventData, ThrowOnError>
): RequestResult<MoveScheduleEventResponses, MoveScheduleEventErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		MoveScheduleEventResponses,
		MoveScheduleEventErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/{event_id}/move',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Update a schedule event
 *
 * Updates a schedule event's skip state. Set `is_skipped` to true to skip the event or false to restore it. Note: the currently active event cannot be skipped.
 */
export const updateScheduleEvent = <ThrowOnError extends boolean = false>(
	options: Options<UpdateScheduleEventData, ThrowOnError>
): RequestResult<UpdateScheduleEventResponses, UpdateScheduleEventErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		UpdateScheduleEventResponses,
		UpdateScheduleEventErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/{event_id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * List schedule audit log
 *
 * Returns a history of all modifications made to the schedule, including skips, moves, and status changes.
 */
export const listScheduleChanges = <ThrowOnError extends boolean = false>(
	options?: Options<ListScheduleChangesData, ThrowOnError>
): RequestResult<ListScheduleChangesResponses, ListScheduleChangesErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListScheduleChangesResponses,
		ListScheduleChangesErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/changes/',
		...options
	});

/**
 * Undo a specific schedule change
 *
 * Reverts a previously made change to the schedule using its unique change ID.
 */
export const undoScheduleChange = <ThrowOnError extends boolean = false>(
	options: Options<UndoScheduleChangeData, ThrowOnError>
): RequestResult<UndoScheduleChangeResponses, UndoScheduleChangeErrors, ThrowOnError> =>
	(options.client ?? client).delete<
		UndoScheduleChangeResponses,
		UndoScheduleChangeErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/changes/{schedule_change_id}',
		...options
	});

/**
 * List the current user's subscriptions
 *
 * Returns every schedule event the current user is subscribed to. Served separately from the schedule so the schedule itself stays universal and cacheable offline.
 */
export const getSubscriptions = <ThrowOnError extends boolean = false>(
	options?: Options<GetSubscriptionsData, ThrowOnError>
): RequestResult<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetSubscriptionsResponses, GetSubscriptionsErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/subscriptions/',
		...options
	});

/**
 * Create a new event subscription
 *
 * Subscribes the current user to a specific schedule event. Prevents duplicate subscriptions.
 */
export const newSubscription = <ThrowOnError extends boolean = false>(
	options: Options<NewSubscriptionData, ThrowOnError>
): RequestResult<NewSubscriptionResponses, NewSubscriptionErrors, ThrowOnError> =>
	(options.client ?? client).post<NewSubscriptionResponses, NewSubscriptionErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/subscriptions/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Remove a subscription
 *
 * Deletes an existing subscription by its unique ID.
 */
export const deleteSubscription = <ThrowOnError extends boolean = false>(
	options: Options<DeleteSubscriptionData, ThrowOnError>
): RequestResult<DeleteSubscriptionResponses, DeleteSubscriptionErrors, ThrowOnError> =>
	(options.client ?? client).delete<
		DeleteSubscriptionResponses,
		DeleteSubscriptionErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/subscriptions/{subscription_id}',
		...options
	});

/**
 * Import Schedule
 */
export const importSchedule = <ThrowOnError extends boolean = false>(
	options: Options<ImportScheduleData, ThrowOnError>
): RequestResult<ImportScheduleResponses, ImportScheduleErrors, ThrowOnError> =>
	(options.client ?? client).post<ImportScheduleResponses, ImportScheduleErrors, ThrowOnError>({
		...formDataBodySerializer,
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/schedule/import',
		...options,
		headers: {
			'Content-Type': null,
			...options.headers
		}
	});

/**
 * Get current voting state
 *
 * Retrieves the current phase of the voting process (e.g., active, closed) and reasoning.
 */
export const getVotingStatus = <ThrowOnError extends boolean = false>(
	options?: Options<GetVotingStatusData, ThrowOnError>
): RequestResult<GetVotingStatusResponses, GetVotingStatusErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetVotingStatusResponses, GetVotingStatusErrors, ThrowOnError>({
		url: '/voting/status',
		...options
	});

/**
 * List all nominations for the current vote
 *
 * Retrieves a list of all candidates or items eligible for voting in the current session.
 */
export const listVotingNominations = <ThrowOnError extends boolean = false>(
	options?: Options<ListVotingNominationsData, ThrowOnError>
): RequestResult<ListVotingNominationsResponses, ListVotingNominationsErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListVotingNominationsResponses,
		ListVotingNominationsErrors,
		ThrowOnError
	>({ url: '/voting/nominations', ...options });

/**
 * Get voting nomination details
 *
 * Retrieves detailed information about a specific nomination.
 */
export const getVotingNomination = <ThrowOnError extends boolean = false>(
	options: Options<GetVotingNominationData, ThrowOnError>
): RequestResult<GetVotingNominationResponses, GetVotingNominationErrors, ThrowOnError> =>
	(options.client ?? client).get<
		GetVotingNominationResponses,
		GetVotingNominationErrors,
		ThrowOnError
	>({ url: '/voting/nominations/{nomination_code}', ...options });

/**
 * Cast a vote
 *
 * Submits a vote for the given participant. The nomination is derived from the participant.
 */
export const addVote = <ThrowOnError extends boolean = false>(
	options: Options<AddVoteData, ThrowOnError>
): RequestResult<AddVoteResponses, AddVoteErrors, ThrowOnError> =>
	(options.client ?? client).post<AddVoteResponses, AddVoteErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/voting/votes',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Cancel a vote
 *
 * Removes a previously cast vote by its ID.
 */
export const cancelVote = <ThrowOnError extends boolean = false>(
	options: Options<CancelVoteData, ThrowOnError>
): RequestResult<CancelVoteResponses, CancelVoteErrors, ThrowOnError> =>
	(options.client ?? client).delete<CancelVoteResponses, CancelVoteErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/voting/votes/{vote_id}',
		...options
	});

/**
 * Get the organizer voting dashboard
 *
 * Voting time range, the leading participant in each votable nomination, and the size of the prize-draw pool. Requires voting:manage.
 */
export const getVotingDashboard = <ThrowOnError extends boolean = false>(
	options?: Options<GetVotingDashboardData, ThrowOnError>
): RequestResult<GetVotingDashboardResponses, GetVotingDashboardErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		GetVotingDashboardResponses,
		GetVotingDashboardErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/voting/dashboard',
		...options
	});

/**
 * Set voting time range
 *
 * Sets the time range during which visitors can vote. Requires voting:manage.
 */
export const setVotingTimeRange = <ThrowOnError extends boolean = false>(
	options: Options<SetVotingTimeRangeData, ThrowOnError>
): RequestResult<SetVotingTimeRangeResponses, SetVotingTimeRangeErrors, ThrowOnError> =>
	(options.client ?? client).patch<
		SetVotingTimeRangeResponses,
		SetVotingTimeRangeErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/voting/dashboard',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Draw a random voting-contest winner
 *
 * Picks one random user who voted in every votable nomination. Stateless — repeated draws may return the same user. Requires voting:manage.
 */
export const drawVotingContestWinner = <ThrowOnError extends boolean = false>(
	options?: Options<DrawVotingContestWinnerData, ThrowOnError>
): RequestResult<DrawVotingContestWinnerResponses, DrawVotingContestWinnerErrors, ThrowOnError> =>
	(options?.client ?? client).post<
		DrawVotingContestWinnerResponses,
		DrawVotingContestWinnerErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/voting/contest/draw',
		...options
	});

/**
 * Process TicketsCloud webhook
 *
 * Handles incoming webhook events from TicketsCloud ticketing system.
 */
export const processTcloudOrder = <ThrowOnError extends boolean = false>(
	options: Options<ProcessTcloudOrderData, ThrowOnError>
): RequestResult<ProcessTcloudOrderResponses, ProcessTcloudOrderErrors, ThrowOnError> =>
	(options.client ?? client).post<
		ProcessTcloudOrderResponses,
		ProcessTcloudOrderErrors,
		ThrowOnError
	>({
		url: '/webhooks/tcloud/{token}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * List user notifications
 *
 * Returns a paginated list of notifications for the authenticated user.
 */
export const listUserNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<ListUserNotificationsData, ThrowOnError>
): RequestResult<ListUserNotificationsResponses, ListUserNotificationsErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		ListUserNotificationsResponses,
		ListUserNotificationsErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/',
		...options
	});

/**
 * Count unread notifications
 *
 * Returns the total number of unread notifications for the authenticated user, independent of any page size — the bell badge is driven by this.
 */
export const countUnreadNotifications = <ThrowOnError extends boolean = false>(
	options?: Options<CountUnreadNotificationsData, ThrowOnError>
): RequestResult<CountUnreadNotificationsResponses, CountUnreadNotificationsErrors, ThrowOnError> =>
	(options?.client ?? client).get<
		CountUnreadNotificationsResponses,
		CountUnreadNotificationsErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/unread-count',
		...options
	});

/**
 * Mark all notifications as read
 *
 * Marks all unread notifications for the authenticated user as read.
 */
export const markAllNotificationsRead = <ThrowOnError extends boolean = false>(
	options?: Options<MarkAllNotificationsReadData, ThrowOnError>
): RequestResult<MarkAllNotificationsReadResponses, MarkAllNotificationsReadErrors, ThrowOnError> =>
	(options?.client ?? client).post<
		MarkAllNotificationsReadResponses,
		MarkAllNotificationsReadErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/mark-all-read',
		...options
	});

/**
 * Mark specific notifications as read
 *
 * Marks the given notifications as read for the authenticated user. Used when opening the notifications panel or page marks the visible items seen.
 */
export const markNotificationsRead = <ThrowOnError extends boolean = false>(
	options: Options<MarkNotificationsReadData, ThrowOnError>
): RequestResult<MarkNotificationsReadResponses, MarkNotificationsReadErrors, ThrowOnError> =>
	(options.client ?? client).post<
		MarkNotificationsReadResponses,
		MarkNotificationsReadErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/mark-read',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Send test notification
 *
 * Creates a test notification for the authenticated user and sends it through all connected channels.
 */
export const sendTestNotification = <ThrowOnError extends boolean = false>(
	options?: Options<SendTestNotificationData, ThrowOnError>
): RequestResult<SendTestNotificationResponses, SendTestNotificationErrors, ThrowOnError> =>
	(options?.client ?? client).post<
		SendTestNotificationResponses,
		SendTestNotificationErrors,
		ThrowOnError
	>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/test',
		...options
	});

/**
 * List broadcasts
 *
 * Returns organizer broadcasts newest-first, paginated. Schedule-change fan-outs are excluded — only role-targeted broadcasts appear.
 */
export const listBroadcasts = <ThrowOnError extends boolean = false>(
	options?: Options<ListBroadcastsData, ThrowOnError>
): RequestResult<ListBroadcastsResponses, ListBroadcastsErrors, ThrowOnError> =>
	(options?.client ?? client).get<ListBroadcastsResponses, ListBroadcastsErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/broadcast',
		...options
	});

/**
 * Send broadcast notification
 *
 * Creates a new mailing broadcast for specified user roles.
 */
export const sendBroadcast = <ThrowOnError extends boolean = false>(
	options: Options<SendBroadcastData, ThrowOnError>
): RequestResult<SendBroadcastResponses, SendBroadcastErrors, ThrowOnError> =>
	(options.client ?? client).post<SendBroadcastResponses, SendBroadcastErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/broadcast',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Cancel a mailing
 *
 * Cancels a mailing: marks it cancelled and deletes its still-undelivered notifications. Messages already delivered to a device cannot be recalled.
 */
export const cancelMailing = <ThrowOnError extends boolean = false>(
	options: Options<CancelMailingData, ThrowOnError>
): RequestResult<CancelMailingResponses, CancelMailingErrors, ThrowOnError> =>
	(options.client ?? client).post<CancelMailingResponses, CancelMailingErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/notifications/broadcast/{mailing_id}/cancel',
		...options
	});

/**
 * Unsubscribe from push notifications
 *
 * Removes a push subscription endpoint for the authenticated user.
 */
export const unsubscribe = <ThrowOnError extends boolean = false>(
	options: Options<UnsubscribeData, ThrowOnError>
): RequestResult<UnsubscribeResponses, UnsubscribeErrors, ThrowOnError> =>
	(options.client ?? client).delete<UnsubscribeResponses, UnsubscribeErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/push/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Check push subscription
 *
 * Reports whether the given endpoint is registered for the authenticated user. The client only needs this yes/no answer for its own device, so the full subscription list (incl. its keys) is not exposed.
 */
export const checkSubscription = <ThrowOnError extends boolean = false>(
	options: Options<CheckSubscriptionData, ThrowOnError>
): RequestResult<CheckSubscriptionResponses, CheckSubscriptionErrors, ThrowOnError> =>
	(options.client ?? client).get<CheckSubscriptionResponses, CheckSubscriptionErrors, ThrowOnError>(
		{
			security: [
				{
					in: 'cookie',
					name: 'session_id',
					type: 'apiKey'
				}
			],
			url: '/push/',
			...options
		}
	);

/**
 * Subscribe to push notifications
 *
 * Registers a push subscription endpoint for the authenticated user's device.
 */
export const subscribe = <ThrowOnError extends boolean = false>(
	options: Options<SubscribeData, ThrowOnError>
): RequestResult<SubscribeResponses, SubscribeErrors, ThrowOnError> =>
	(options.client ?? client).post<SubscribeResponses, SubscribeErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/push/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * List app feedback
 *
 * Returns a paginated list of feedback submitted by users, newest first. Requires the feedback:read permission.
 */
export const listFeedback = <ThrowOnError extends boolean = false>(
	options?: Options<ListFeedbackData, ThrowOnError>
): RequestResult<ListFeedbackResponses, ListFeedbackErrors, ThrowOnError> =>
	(options?.client ?? client).get<ListFeedbackResponses, ListFeedbackErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/feedback/',
		...options
	});

/**
 * Submit app feedback
 *
 * Submits free-text feedback about the app from the current user.
 */
export const submitFeedback = <ThrowOnError extends boolean = false>(
	options: Options<SubmitFeedbackData, ThrowOnError>
): RequestResult<SubmitFeedbackResponses, SubmitFeedbackErrors, ThrowOnError> =>
	(options.client ?? client).post<SubmitFeedbackResponses, SubmitFeedbackErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/feedback/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * Generate tickets
 *
 * Generates a batch of new tickets for the given role. Requires the 'tickets:generate' permission. Returns the created barcodes.
 */
export const generateTickets = <ThrowOnError extends boolean = false>(
	options: Options<GenerateTicketsData, ThrowOnError>
): RequestResult<GenerateTicketsResponses, GenerateTicketsErrors, ThrowOnError> =>
	(options.client ?? client).post<GenerateTicketsResponses, GenerateTicketsErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/tickets/generate',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers
		}
	});

/**
 * List sync sources with their last run
 *
 * Returns every vendor sync source, whether it is configured for this deployment, and its most recent run. Requires the 'sync:run' permission.
 */
export const getSyncSources = <ThrowOnError extends boolean = false>(
	options?: Options<GetSyncSourcesData, ThrowOnError>
): RequestResult<GetSyncSourcesResponses, GetSyncSourcesErrors, ThrowOnError> =>
	(options?.client ?? client).get<GetSyncSourcesResponses, GetSyncSourcesErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/sync/sources',
		...options
	});

/**
 * Request a sync
 *
 * Queues a sync of the given source and returns immediately with the created run. The work runs in the stream service, so progress arrives over SSE ('sync_run_updated') and the run's final state is readable from GET /sync/sources. Requires the 'sync:run' permission.
 */
export const requestSync = <ThrowOnError extends boolean = false>(
	options: Options<RequestSyncData, ThrowOnError>
): RequestResult<RequestSyncResponses, RequestSyncErrors, ThrowOnError> =>
	(options.client ?? client).post<RequestSyncResponses, RequestSyncErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/sync/{source}',
		...options
	});

/**
 * List users
 *
 * Paginated, searchable directory of all users. Search matches a case-insensitive substring of the username or email. Requires users:read.
 */
export const listUsers = <ThrowOnError extends boolean = false>(
	options?: Options<ListUsersData, ThrowOnError>
): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> =>
	(options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/users/',
		...options
	});

/**
 * Count online users
 *
 * How many users hold a live connection right now, for the organiser dashboard. Approximate and ephemeral. Any authenticated user.
 */
export const countOnlineUsers = <ThrowOnError extends boolean = false>(
	options?: Options<CountOnlineUsersData, ThrowOnError>
): RequestResult<CountOnlineUsersResponses, CountOnlineUsersErrors, ThrowOnError> =>
	(options?.client ?? client).get<CountOnlineUsersResponses, CountOnlineUsersErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/users/online-count',
		...options
	});

/**
 * Get user details
 *
 * Profile basics and linked external accounts for one user. Requires users:read.
 */
export const getUser = <ThrowOnError extends boolean = false>(
	options: Options<GetUserData, ThrowOnError>
): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> =>
	(options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
		security: [
			{
				in: 'cookie',
				name: 'session_id',
				type: 'apiKey'
			}
		],
		url: '/users/{user_id}',
		...options
	});
