import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';

// Mirrors openapi-typescript's own `--check` flag, which we can't use directly:
// the Blob transform below needs the Node API, not the CLI. Same semantics —
// compare instead of write, exit non-zero when the committed file is stale.
const checkOnly = process.argv.includes('--check');

const schemaPath = new URL('../../shared/openapi/openapi.json', import.meta.url);
const outputPath = new URL('../src/lib/api/schema.d.ts', import.meta.url);
const GENERATED_FILE_HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

const BLOB = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier('Blob'));
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull());

function isBlobSchema(schemaObject) {
	// FastAPI exports file uploads with contentMediaType, while other schemas may use format=binary.
	const schemaWithMediaType = /** @type {{ contentMediaType?: string }} */ (schemaObject);

	return (
		schemaObject.format === 'binary' ||
		(schemaObject.type === 'string' && typeof schemaWithMediaType.contentMediaType === 'string')
	);
}

const ast = await openapiTS(schemaPath, {
	transform(schemaObject) {
		if (!isBlobSchema(schemaObject)) {
			return undefined;
		}

		return schemaObject.nullable ? ts.factory.createUnionTypeNode([BLOB, NULL]) : BLOB;
	}
});

const generated = `${GENERATED_FILE_HEADER}${astToString(ast)}`;

if (checkOnly) {
	const committed = await readFile(outputPath, 'utf8').catch(() => null);

	if (committed !== generated) {
		console.error(
			`${fileURLToPath(outputPath)} is out of date with shared/openapi/openapi.json.\n` +
				'Regenerate it with: just frontend-generate-api'
		);
		process.exit(1);
	}

	console.log(`Up to date: ${fileURLToPath(outputPath)}`);
} else {
	await writeFile(outputPath, generated, 'utf8');

	console.log(`Generated ${fileURLToPath(outputPath)}`);
}
