import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';

const schemaPath = new URL('../../shared/openapi/openapi.json', import.meta.url);
const outputPath = new URL('../src/lib/api/schema.d.ts', import.meta.url);
const GENERATED_FILE_HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

const BLOB = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier('Blob'));
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull());

function isBlobSchema(schemaObject) {
	// FastAPI exports file uploads with contentMediaType, while other schemas may use format=binary.
	const schemaWithMediaType = /** @type {{ contentMediaType?: string }} */ (schemaObject);

	return (
		schemaObject.format === 'binary' ||
		(schemaObject.type === 'string' && typeof schemaWithMediaType.contentMediaType === 'string')
	);
}

const ast = await openapiTS(schemaPath, {
	transform(schemaObject) {
		if (!isBlobSchema(schemaObject)) {
			return undefined;
		}

		return schemaObject.nullable ? ts.factory.createUnionTypeNode([BLOB, NULL]) : BLOB;
	}
});

await writeFile(outputPath, `${GENERATED_FILE_HEADER}${astToString(ast)}`, 'utf8');

console.log(`Generated ${fileURLToPath(outputPath)}`);
