from dataclasses import dataclass
from typing import Self

from fanfan.core.exceptions.tickets import TicketAlreadyUsed
from fanfan.core.models.base import AggregateRoot
from fanfan.core.vo.ticket import TicketId, generate_ticket_barcode, generate_ticket_id
from fanfan.core.vo.user import UserId, UserRole


@dataclass(slots=True, kw_only=True)
class Ticket(AggregateRoot):
    id: TicketId
    barcode: str
    role: UserRole
    used_by_user_id: UserId | None
    issued_by_user_id: UserId | None

    # Ticketscloud
    ticketscloud_ticket_id: str | None

    @classmethod
    def issue(cls, *, role: UserRole, issued_by_user_id: UserId) -> Self:
        """Create a brand-new, unused ticket for a role, issued by an organizer.

        Unlike imported tickets, its barcode is generated by us and it carries no
        vendor id — it exists only so a recipient can link it and take the role.
        """
        return cls(
            id=generate_ticket_id(),
            barcode=generate_ticket_barcode(),
            role=role,
            used_by_user_id=None,
            issued_by_user_id=issued_by_user_id,
            ticketscloud_ticket_id=None,
        )

    @property
    def is_used(self) -> bool:
        return self.used_by_user_id is not None

    def is_used_by(self, user_id: UserId) -> bool:
        return self.used_by_user_id == user_id

    def set_as_used(self, user_id: UserId):
        if self.is_used:
            raise TicketAlreadyUsed
        self.used_by_user_id = user_id

    def unlink(self) -> UserId | None:
        linked_user_id = self.used_by_user_id
        self.used_by_user_id = None
        return linked_user_id
