// This file is auto-generated by @hey-api/openapi-ts

import {
	type InfiniteData,
	infiniteQueryOptions,
	type MutationOptions,
	queryOptions
} from '@tanstack/svelte-query';

import { client } from '../client.gen';
import {
	addVote,
	cancelMailing,
	cancelVote,
	changeCurrentUserEmail,
	changeCurrentUserPassword,
	checkSubscription,
	confirmEmailCode,
	countOnlineUsers,
	countUnreadNotifications,
	debug,
	deleteSubscription,
	drawVotingContestWinner,
	generateTickets,
	getCurrentUser,
	getPublicConfig,
	getSchedule,
	getSettings,
	getSubscriptions,
	getSyncSources,
	getUser,
	getVotingDashboard,
	getVotingNomination,
	getVotingStatus,
	healthCheck,
	importSchedule,
	linkTicket,
	listBroadcasts,
	listFeedback,
	listOauthProviders,
	listScheduleChanges,
	listUserNotifications,
	listUsers,
	listVotingNominations,
	login,
	loginWithCode,
	logoutUser,
	markAllNotificationsRead,
	markNotificationsRead,
	moveScheduleEvent,
	newSubscription,
	oauthCallback,
	type Options,
	processTcloudOrder,
	requestLoginCode,
	requestSync,
	sendBroadcast,
	sendTestNotification,
	setEventAsCurrent,
	setVotingTimeRange,
	startAccountLink,
	startSocialLogin,
	submitFeedback,
	subscribe,
	uncheckCurrentEvent,
	undoScheduleChange,
	unlinkTelegramAccount,
	unlinkVkAccount,
	unsubscribe,
	updateCurrentUser,
	updateCurrentUserSettings,
	updateScheduleEvent,
	updateSettings
} from '../sdk.gen';
import type {
	AddVoteData,
	AddVoteError,
	AddVoteResponse,
	CancelMailingData,
	CancelMailingError,
	CancelMailingResponse,
	CancelVoteData,
	CancelVoteError,
	CancelVoteResponse,
	ChangeCurrentUserEmailData,
	ChangeCurrentUserEmailError,
	ChangeCurrentUserEmailResponse,
	ChangeCurrentUserPasswordData,
	ChangeCurrentUserPasswordError,
	ChangeCurrentUserPasswordResponse,
	CheckSubscriptionData,
	CheckSubscriptionError,
	CheckSubscriptionResponse,
	ConfirmEmailCodeData,
	ConfirmEmailCodeError,
	ConfirmEmailCodeResponse,
	CountOnlineUsersData,
	CountOnlineUsersError,
	CountOnlineUsersResponse,
	CountUnreadNotificationsData,
	CountUnreadNotificationsError,
	CountUnreadNotificationsResponse,
	DebugData,
	DebugError,
	DebugResponse2,
	DeleteSubscriptionData,
	DeleteSubscriptionError,
	DeleteSubscriptionResponse,
	DrawVotingContestWinnerData,
	DrawVotingContestWinnerError,
	DrawVotingContestWinnerResponse,
	GenerateTicketsData,
	GenerateTicketsError,
	GenerateTicketsResponse,
	GetCurrentUserData,
	GetCurrentUserError,
	GetCurrentUserResponse,
	GetPublicConfigData,
	GetPublicConfigError,
	GetPublicConfigResponse,
	GetScheduleData,
	GetScheduleError,
	GetScheduleResponse,
	GetSettingsData,
	GetSettingsError,
	GetSettingsResponse,
	GetSubscriptionsData,
	GetSubscriptionsError,
	GetSubscriptionsResponse,
	GetSyncSourcesData,
	GetSyncSourcesError,
	GetSyncSourcesResponse,
	GetUserData,
	GetUserError,
	GetUserResponse,
	GetVotingDashboardData,
	GetVotingDashboardError,
	GetVotingDashboardResponse,
	GetVotingNominationData,
	GetVotingNominationError,
	GetVotingNominationResponse,
	GetVotingStatusData,
	GetVotingStatusError,
	GetVotingStatusResponse,
	HealthCheckData,
	HealthCheckError,
	HealthCheckResponse2,
	ImportScheduleData,
	ImportScheduleError,
	LinkTicketData,
	LinkTicketError,
	LinkTicketResponse,
	ListBroadcastsData,
	ListBroadcastsError,
	ListBroadcastsResponse,
	ListFeedbackData,
	ListFeedbackError,
	ListFeedbackResponse,
	ListOauthProvidersData,
	ListOauthProvidersError,
	ListOauthProvidersResponse,
	ListScheduleChangesData,
	ListScheduleChangesError,
	ListScheduleChangesResponse,
	ListUserNotificationsData,
	ListUserNotificationsError,
	ListUserNotificationsResponse,
	ListUsersData,
	ListUsersError,
	ListUsersResponse,
	ListVotingNominationsData,
	ListVotingNominationsError,
	ListVotingNominationsResponse,
	LoginData,
	LoginError,
	LoginResponse,
	LoginWithCodeData,
	LoginWithCodeError,
	LoginWithCodeResponse,
	LogoutUserData,
	LogoutUserError,
	LogoutUserResponse,
	MarkAllNotificationsReadData,
	MarkAllNotificationsReadError,
	MarkAllNotificationsReadResponse,
	MarkNotificationsReadData,
	MarkNotificationsReadError,
	MarkNotificationsReadResponse,
	MoveScheduleEventData,
	MoveScheduleEventError,
	MoveScheduleEventResponse,
	NewSubscriptionData,
	NewSubscriptionError,
	NewSubscriptionResponse,
	OauthCallbackData,
	OauthCallbackError,
	ProcessTcloudOrderData,
	ProcessTcloudOrderError,
	ProcessTcloudOrderResponse,
	RequestLoginCodeData,
	RequestLoginCodeError,
	RequestSyncData,
	RequestSyncError,
	RequestSyncResponse,
	SendBroadcastData,
	SendBroadcastError,
	SendBroadcastResponse,
	SendTestNotificationData,
	SendTestNotificationError,
	SendTestNotificationResponse,
	SetEventAsCurrentData,
	SetEventAsCurrentError,
	SetEventAsCurrentResponse,
	SetVotingTimeRangeData,
	SetVotingTimeRangeError,
	SetVotingTimeRangeResponse,
	StartAccountLinkData,
	StartAccountLinkError,
	StartSocialLoginData,
	StartSocialLoginError,
	SubmitFeedbackData,
	SubmitFeedbackError,
	SubmitFeedbackResponse,
	SubscribeData,
	SubscribeError,
	SubscribeResponse,
	UncheckCurrentEventData,
	UncheckCurrentEventError,
	UncheckCurrentEventResponse,
	UndoScheduleChangeData,
	UndoScheduleChangeError,
	UndoScheduleChangeResponse,
	UnlinkTelegramAccountData,
	UnlinkTelegramAccountError,
	UnlinkTelegramAccountResponse,
	UnlinkVkAccountData,
	UnlinkVkAccountError,
	UnlinkVkAccountResponse,
	UnsubscribeData,
	UnsubscribeError,
	UnsubscribeResponse,
	UpdateCurrentUserData,
	UpdateCurrentUserError,
	UpdateCurrentUserResponse,
	UpdateCurrentUserSettingsData,
	UpdateCurrentUserSettingsError,
	UpdateCurrentUserSettingsResponse,
	UpdateScheduleEventData,
	UpdateScheduleEventError,
	UpdateScheduleEventResponse,
	UpdateSettingsData,
	UpdateSettingsError,
	UpdateSettingsResponse
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
	Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
		_id: string;
		_infinite?: boolean;
		tags?: ReadonlyArray<string>;
	}
];

const createQueryKey = <TOptions extends Options>(
	id: string,
	options?: TOptions,
	infinite?: boolean,
	tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
	const params: QueryKey<TOptions>[0] = {
		_id: id,
		baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl
	} as QueryKey<TOptions>[0];
	if (infinite) {
		params._infinite = infinite;
	}
	if (tags) {
		params.tags = tags;
	}
	if (options?.body) {
		params.body = options.body;
	}
	if (options?.headers) {
		params.headers = options.headers;
	}
	if (options?.path) {
		params.path = options.path;
	}
	if (options?.query) {
		params.query = options.query;
	}
	return [params];
};

export const debugQueryKey = (options?: Options<DebugData>) => createQueryKey('debug', options);

/**
 * Debug
 */
export const debugOptions = (options?: Options<DebugData>) =>
	queryOptions<DebugResponse2, DebugError, DebugResponse2, ReturnType<typeof debugQueryKey>>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await debug({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: debugQueryKey(options)
	});

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) =>
	createQueryKey('healthCheck', options);

/**
 * Health Check
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) =>
	queryOptions<
		HealthCheckResponse2,
		HealthCheckError,
		HealthCheckResponse2,
		ReturnType<typeof healthCheckQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await healthCheck({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: healthCheckQueryKey(options)
	});

/**
 * Login and create session
 *
 * Authenticates user with email and password. Sets an HttpOnly cookie with a Redis-backed session id.
 */
export const loginMutation = (
	options?: Partial<Options<LoginData>>
): MutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
	const mutationOptions: MutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
		mutationFn: async (fnOptions) => {
			const { data } = await login({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Confirm user email with code
 *
 * Confirms the new email address using a one-time code received at that address.
 */
export const confirmEmailCodeMutation = (
	options?: Partial<Options<ConfirmEmailCodeData>>
): MutationOptions<
	ConfirmEmailCodeResponse,
	ConfirmEmailCodeError,
	Options<ConfirmEmailCodeData>
> => {
	const mutationOptions: MutationOptions<
		ConfirmEmailCodeResponse,
		ConfirmEmailCodeError,
		Options<ConfirmEmailCodeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await confirmEmailCode({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Request email login code
 *
 * Sends a one-time six-digit sign-in code to the requested email address. Creates an account automatically when the email is new. The code is sent before the response returns, so a delivery failure is reported instead of being swallowed.
 */
export const requestLoginCodeMutation = (
	options?: Partial<Options<RequestLoginCodeData>>
): MutationOptions<unknown, RequestLoginCodeError, Options<RequestLoginCodeData>> => {
	const mutationOptions: MutationOptions<
		unknown,
		RequestLoginCodeError,
		Options<RequestLoginCodeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await requestLoginCode({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Login with email code
 *
 * Consumes a one-time email code and sets session cookie.
 */
export const loginWithCodeMutation = (
	options?: Partial<Options<LoginWithCodeData>>
): MutationOptions<LoginWithCodeResponse, LoginWithCodeError, Options<LoginWithCodeData>> => {
	const mutationOptions: MutationOptions<
		LoginWithCodeResponse,
		LoginWithCodeError,
		Options<LoginWithCodeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await loginWithCode({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Logout user
 *
 * Clears session cookie and removes Redis session state.
 */
export const logoutUserMutation = (
	options?: Partial<Options<LogoutUserData>>
): MutationOptions<LogoutUserResponse, LogoutUserError, Options<LogoutUserData>> => {
	const mutationOptions: MutationOptions<
		LogoutUserResponse,
		LogoutUserError,
		Options<LogoutUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await logoutUser({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listOauthProvidersQueryKey = (options?: Options<ListOauthProvidersData>) =>
	createQueryKey('listOauthProviders', options);

/**
 * List enabled social login providers
 *
 * Returns the social login providers this deployment offers, in display order. The login screen renders one button per provider; a provider missing here is disabled and its start endpoint is rejected. Unauthenticated on purpose — it only reveals which buttons to draw, which is not sensitive.
 */
export const listOauthProvidersOptions = (options?: Options<ListOauthProvidersData>) =>
	queryOptions<
		ListOauthProvidersResponse,
		ListOauthProvidersError,
		ListOauthProvidersResponse,
		ReturnType<typeof listOauthProvidersQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listOauthProviders({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listOauthProvidersQueryKey(options)
	});

export const startSocialLoginQueryKey = (options: Options<StartSocialLoginData>) =>
	createQueryKey('startSocialLogin', options);

/**
 * Start social login
 *
 * Redirects the browser to the provider's OAuth page to begin signing in. The provider then calls back to the callback endpoint to finish. If the redirect cannot be built the browser goes back to the login page with an `oauthLoginError` query param instead.
 */
export const startSocialLoginOptions = (options: Options<StartSocialLoginData>) =>
	queryOptions<
		unknown,
		StartSocialLoginError,
		unknown,
		ReturnType<typeof startSocialLoginQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await startSocialLogin({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: startSocialLoginQueryKey(options)
	});

export const oauthCallbackQueryKey = (options: Options<OauthCallbackData>) =>
	createQueryKey('oauthCallback', options);

/**
 * Finish a social login or account link
 *
 * OAuth callback shared by both flows; which one it is comes from the intent stored in the OAuth state, never from the request. On a login it sets the session cookie and redirects to the app root; on a link it attaches the account and redirects to the profile page. Every failure also redirects, carrying an `oauthLoginError` or `oauthLinkError` query param the frontend turns into a toast; this route never answers with an error body, because the browser would render it as the page. Invoked by the provider, not called directly by the frontend.
 */
export const oauthCallbackOptions = (options: Options<OauthCallbackData>) =>
	queryOptions<unknown, OauthCallbackError, unknown, ReturnType<typeof oauthCallbackQueryKey>>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await oauthCallback({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: oauthCallbackQueryKey(options)
	});

export const getPublicConfigQueryKey = (options?: Options<GetPublicConfigData>) =>
	createQueryKey('getPublicConfig', options);

/**
 * Get public config
 *
 * Returns the public festival config the SPA needs before login.
 */
export const getPublicConfigOptions = (options?: Options<GetPublicConfigData>) =>
	queryOptions<
		GetPublicConfigResponse,
		GetPublicConfigError,
		GetPublicConfigResponse,
		ReturnType<typeof getPublicConfigQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getPublicConfig({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getPublicConfigQueryKey(options)
	});

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
	createQueryKey('getCurrentUser', options);

/**
 * Get current user
 *
 * Retrieves the currently authenticated user's profile information.
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) =>
	queryOptions<
		GetCurrentUserResponse,
		GetCurrentUserError,
		GetCurrentUserResponse,
		ReturnType<typeof getCurrentUserQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getCurrentUser({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getCurrentUserQueryKey(options)
	});

/**
 * Update current user
 *
 * Updates the currently authenticated user's profile information.
 */
export const updateCurrentUserMutation = (
	options?: Partial<Options<UpdateCurrentUserData>>
): MutationOptions<
	UpdateCurrentUserResponse,
	UpdateCurrentUserError,
	Options<UpdateCurrentUserData>
> => {
	const mutationOptions: MutationOptions<
		UpdateCurrentUserResponse,
		UpdateCurrentUserError,
		Options<UpdateCurrentUserData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await updateCurrentUser({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Update current user settings
 *
 * Updates the currently authenticated user's profile settings.
 */
export const updateCurrentUserSettingsMutation = (
	options?: Partial<Options<UpdateCurrentUserSettingsData>>
): MutationOptions<
	UpdateCurrentUserSettingsResponse,
	UpdateCurrentUserSettingsError,
	Options<UpdateCurrentUserSettingsData>
> => {
	const mutationOptions: MutationOptions<
		UpdateCurrentUserSettingsResponse,
		UpdateCurrentUserSettingsError,
		Options<UpdateCurrentUserSettingsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await updateCurrentUserSettings({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Change current user password
 *
 * Changes the authenticated user's password. Requires the current password for verification when one is already set.
 */
export const changeCurrentUserPasswordMutation = (
	options?: Partial<Options<ChangeCurrentUserPasswordData>>
): MutationOptions<
	ChangeCurrentUserPasswordResponse,
	ChangeCurrentUserPasswordError,
	Options<ChangeCurrentUserPasswordData>
> => {
	const mutationOptions: MutationOptions<
		ChangeCurrentUserPasswordResponse,
		ChangeCurrentUserPasswordError,
		Options<ChangeCurrentUserPasswordData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await changeCurrentUserPassword({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Change current user email
 *
 * Sends a confirmation code to the new address. The stored email changes only once that code is confirmed. The code is sent before the response returns, so a delivery failure is reported instead of swallowed.
 */
export const changeCurrentUserEmailMutation = (
	options?: Partial<Options<ChangeCurrentUserEmailData>>
): MutationOptions<
	ChangeCurrentUserEmailResponse,
	ChangeCurrentUserEmailError,
	Options<ChangeCurrentUserEmailData>
> => {
	const mutationOptions: MutationOptions<
		ChangeCurrentUserEmailResponse,
		ChangeCurrentUserEmailError,
		Options<ChangeCurrentUserEmailData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await changeCurrentUserEmail({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const startAccountLinkQueryKey = (options: Options<StartAccountLinkData>) =>
	createQueryKey('startAccountLink', options);

/**
 * Start account linking
 *
 * Redirects the browser to the provider's OAuth page to begin linking the account to the current user. The provider then calls back to the shared callback (`/auth/oauth/{provider}/callback`) to finish. If the redirect cannot be built the browser goes back to the profile page with an `oauthLinkError` query param instead.
 */
export const startAccountLinkOptions = (options: Options<StartAccountLinkData>) =>
	queryOptions<
		unknown,
		StartAccountLinkError,
		unknown,
		ReturnType<typeof startAccountLinkQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await startAccountLink({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: startAccountLinkQueryKey(options)
	});

/**
 * Unlink Telegram account
 *
 * Unlinks the Telegram account from the currently authenticated user.
 */
export const unlinkTelegramAccountMutation = (
	options?: Partial<Options<UnlinkTelegramAccountData>>
): MutationOptions<
	UnlinkTelegramAccountResponse,
	UnlinkTelegramAccountError,
	Options<UnlinkTelegramAccountData>
> => {
	const mutationOptions: MutationOptions<
		UnlinkTelegramAccountResponse,
		UnlinkTelegramAccountError,
		Options<UnlinkTelegramAccountData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await unlinkTelegramAccount({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Unlink VK account
 *
 * Unlinks the VK account from the currently authenticated user.
 */
export const unlinkVkAccountMutation = (
	options?: Partial<Options<UnlinkVkAccountData>>
): MutationOptions<UnlinkVkAccountResponse, UnlinkVkAccountError, Options<UnlinkVkAccountData>> => {
	const mutationOptions: MutationOptions<
		UnlinkVkAccountResponse,
		UnlinkVkAccountError,
		Options<UnlinkVkAccountData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await unlinkVkAccount({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Link ticket
 *
 * Links provided ticket to current user.
 */
export const linkTicketMutation = (
	options?: Partial<Options<LinkTicketData>>
): MutationOptions<LinkTicketResponse, LinkTicketError, Options<LinkTicketData>> => {
	const mutationOptions: MutationOptions<
		LinkTicketResponse,
		LinkTicketError,
		Options<LinkTicketData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await linkTicket({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getSettingsQueryKey = (options?: Options<GetSettingsData>) =>
	createQueryKey('getSettings', options);

/**
 * Get festival settings
 *
 * Returns the current festival settings that organizers can manage.
 */
export const getSettingsOptions = (options?: Options<GetSettingsData>) =>
	queryOptions<
		GetSettingsResponse,
		GetSettingsError,
		GetSettingsResponse,
		ReturnType<typeof getSettingsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getSettings({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getSettingsQueryKey(options)
	});

/**
 * Update festival settings
 *
 * Updates festival settings that are available to organizers.
 */
export const updateSettingsMutation = (
	options?: Partial<Options<UpdateSettingsData>>
): MutationOptions<UpdateSettingsResponse, UpdateSettingsError, Options<UpdateSettingsData>> => {
	const mutationOptions: MutationOptions<
		UpdateSettingsResponse,
		UpdateSettingsError,
		Options<UpdateSettingsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await updateSettings({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getScheduleQueryKey = (options?: Options<GetScheduleData>) =>
	createQueryKey('getSchedule', options);

/**
 * Get current schedule
 *
 * Retrieves the full schedule using the GetSchedule interactor.
 */
export const getScheduleOptions = (options?: Options<GetScheduleData>) =>
	queryOptions<
		GetScheduleResponse,
		GetScheduleError,
		GetScheduleResponse,
		ReturnType<typeof getScheduleQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getSchedule({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getScheduleQueryKey(options)
	});

/**
 * Set specific event as current
 *
 * Updates the schedule state to mark a specific event as active. Validates timing and event status.
 */
export const setEventAsCurrentMutation = (
	options?: Partial<Options<SetEventAsCurrentData>>
): MutationOptions<
	SetEventAsCurrentResponse,
	SetEventAsCurrentError,
	Options<SetEventAsCurrentData>
> => {
	const mutationOptions: MutationOptions<
		SetEventAsCurrentResponse,
		SetEventAsCurrentError,
		Options<SetEventAsCurrentData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await setEventAsCurrent({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Unset current schedule event
 *
 * Clears the currently active event from the schedule. Subject to rate limiting.
 */
export const uncheckCurrentEventMutation = (
	options?: Partial<Options<UncheckCurrentEventData>>
): MutationOptions<
	UncheckCurrentEventResponse,
	UncheckCurrentEventError,
	Options<UncheckCurrentEventData>
> => {
	const mutationOptions: MutationOptions<
		UncheckCurrentEventResponse,
		UncheckCurrentEventError,
		Options<UncheckCurrentEventData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await uncheckCurrentEvent({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Reorder schedule event
 *
 * Moves an event to a new position in the sequence, specifically after the provided event ID.
 */
export const moveScheduleEventMutation = (
	options?: Partial<Options<MoveScheduleEventData>>
): MutationOptions<
	MoveScheduleEventResponse,
	MoveScheduleEventError,
	Options<MoveScheduleEventData>
> => {
	const mutationOptions: MutationOptions<
		MoveScheduleEventResponse,
		MoveScheduleEventError,
		Options<MoveScheduleEventData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await moveScheduleEvent({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Update a schedule event
 *
 * Updates a schedule event's skip state. Set `is_skipped` to true to skip the event or false to restore it. Note: the currently active event cannot be skipped.
 */
export const updateScheduleEventMutation = (
	options?: Partial<Options<UpdateScheduleEventData>>
): MutationOptions<
	UpdateScheduleEventResponse,
	UpdateScheduleEventError,
	Options<UpdateScheduleEventData>
> => {
	const mutationOptions: MutationOptions<
		UpdateScheduleEventResponse,
		UpdateScheduleEventError,
		Options<UpdateScheduleEventData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await updateScheduleEvent({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listScheduleChangesQueryKey = (options?: Options<ListScheduleChangesData>) =>
	createQueryKey('listScheduleChanges', options);

/**
 * List schedule audit log
 *
 * Returns a history of all modifications made to the schedule, including skips, moves, and status changes.
 */
export const listScheduleChangesOptions = (options?: Options<ListScheduleChangesData>) =>
	queryOptions<
		ListScheduleChangesResponse,
		ListScheduleChangesError,
		ListScheduleChangesResponse,
		ReturnType<typeof listScheduleChangesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listScheduleChanges({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listScheduleChangesQueryKey(options)
	});

const createInfiniteParams = <
	K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>
>(
	queryKey: QueryKey<Options>,
	page: K
) => {
	const params = { ...queryKey[0] };
	if (page.body) {
		params.body = {
			...(queryKey[0].body as any),
			...(page.body as any)
		};
	}
	if (page.headers) {
		params.headers = {
			...queryKey[0].headers,
			...page.headers
		};
	}
	if (page.path) {
		params.path = {
			...(queryKey[0].path as any),
			...(page.path as any)
		};
	}
	if (page.query) {
		params.query = {
			...(queryKey[0].query as any),
			...(page.query as any)
		};
	}
	return params as unknown as typeof page;
};

export const listScheduleChangesInfiniteQueryKey = (
	options?: Options<ListScheduleChangesData>
): QueryKey<Options<ListScheduleChangesData>> =>
	createQueryKey('listScheduleChanges', options, true);

/**
 * List schedule audit log
 *
 * Returns a history of all modifications made to the schedule, including skips, moves, and status changes.
 */
export const listScheduleChangesInfiniteOptions = (options?: Options<ListScheduleChangesData>) => {
	const opts = infiniteQueryOptions<
		ListScheduleChangesResponse,
		ListScheduleChangesError,
		InfiniteData<ListScheduleChangesResponse>,
		QueryKey<Options<ListScheduleChangesData>>,
		| number
		| Pick<QueryKey<Options<ListScheduleChangesData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ListScheduleChangesData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam
								}
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await listScheduleChanges({
					...options,
					...params,
					signal,
					throwOnError: true
				});
				return data;
			},
			queryKey: listScheduleChangesInfiniteQueryKey(options)
		}
	);
	return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Undo a specific schedule change
 *
 * Reverts a previously made change to the schedule using its unique change ID.
 */
export const undoScheduleChangeMutation = (
	options?: Partial<Options<UndoScheduleChangeData>>
): MutationOptions<
	UndoScheduleChangeResponse,
	UndoScheduleChangeError,
	Options<UndoScheduleChangeData>
> => {
	const mutationOptions: MutationOptions<
		UndoScheduleChangeResponse,
		UndoScheduleChangeError,
		Options<UndoScheduleChangeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await undoScheduleChange({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getSubscriptionsQueryKey = (options?: Options<GetSubscriptionsData>) =>
	createQueryKey('getSubscriptions', options);

/**
 * List the current user's subscriptions
 *
 * Returns every schedule event the current user is subscribed to. Served separately from the schedule so the schedule itself stays universal and cacheable offline.
 */
export const getSubscriptionsOptions = (options?: Options<GetSubscriptionsData>) =>
	queryOptions<
		GetSubscriptionsResponse,
		GetSubscriptionsError,
		GetSubscriptionsResponse,
		ReturnType<typeof getSubscriptionsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getSubscriptions({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getSubscriptionsQueryKey(options)
	});

/**
 * Create a new event subscription
 *
 * Subscribes the current user to a specific schedule event. Prevents duplicate subscriptions.
 */
export const newSubscriptionMutation = (
	options?: Partial<Options<NewSubscriptionData>>
): MutationOptions<NewSubscriptionResponse, NewSubscriptionError, Options<NewSubscriptionData>> => {
	const mutationOptions: MutationOptions<
		NewSubscriptionResponse,
		NewSubscriptionError,
		Options<NewSubscriptionData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await newSubscription({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Remove a subscription
 *
 * Deletes an existing subscription by its unique ID.
 */
export const deleteSubscriptionMutation = (
	options?: Partial<Options<DeleteSubscriptionData>>
): MutationOptions<
	DeleteSubscriptionResponse,
	DeleteSubscriptionError,
	Options<DeleteSubscriptionData>
> => {
	const mutationOptions: MutationOptions<
		DeleteSubscriptionResponse,
		DeleteSubscriptionError,
		Options<DeleteSubscriptionData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await deleteSubscription({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Import Schedule
 */
export const importScheduleMutation = (
	options?: Partial<Options<ImportScheduleData>>
): MutationOptions<unknown, ImportScheduleError, Options<ImportScheduleData>> => {
	const mutationOptions: MutationOptions<
		unknown,
		ImportScheduleError,
		Options<ImportScheduleData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await importSchedule({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getVotingStatusQueryKey = (options?: Options<GetVotingStatusData>) =>
	createQueryKey('getVotingStatus', options);

/**
 * Get current voting state
 *
 * Retrieves the current phase of the voting process (e.g., active, closed) and reasoning.
 */
export const getVotingStatusOptions = (options?: Options<GetVotingStatusData>) =>
	queryOptions<
		GetVotingStatusResponse,
		GetVotingStatusError,
		GetVotingStatusResponse,
		ReturnType<typeof getVotingStatusQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getVotingStatus({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getVotingStatusQueryKey(options)
	});

export const listVotingNominationsQueryKey = (options?: Options<ListVotingNominationsData>) =>
	createQueryKey('listVotingNominations', options);

/**
 * List all nominations for the current vote
 *
 * Retrieves a list of all candidates or items eligible for voting in the current session.
 */
export const listVotingNominationsOptions = (options?: Options<ListVotingNominationsData>) =>
	queryOptions<
		ListVotingNominationsResponse,
		ListVotingNominationsError,
		ListVotingNominationsResponse,
		ReturnType<typeof listVotingNominationsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listVotingNominations({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listVotingNominationsQueryKey(options)
	});

export const getVotingNominationQueryKey = (options: Options<GetVotingNominationData>) =>
	createQueryKey('getVotingNomination', options);

/**
 * Get voting nomination details
 *
 * Retrieves detailed information about a specific nomination.
 */
export const getVotingNominationOptions = (options: Options<GetVotingNominationData>) =>
	queryOptions<
		GetVotingNominationResponse,
		GetVotingNominationError,
		GetVotingNominationResponse,
		ReturnType<typeof getVotingNominationQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getVotingNomination({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getVotingNominationQueryKey(options)
	});

/**
 * Cast a vote
 *
 * Submits a vote for the given participant. The nomination is derived from the participant.
 */
export const addVoteMutation = (
	options?: Partial<Options<AddVoteData>>
): MutationOptions<AddVoteResponse, AddVoteError, Options<AddVoteData>> => {
	const mutationOptions: MutationOptions<AddVoteResponse, AddVoteError, Options<AddVoteData>> = {
		mutationFn: async (fnOptions) => {
			const { data } = await addVote({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Cancel a vote
 *
 * Removes a previously cast vote by its ID.
 */
export const cancelVoteMutation = (
	options?: Partial<Options<CancelVoteData>>
): MutationOptions<CancelVoteResponse, CancelVoteError, Options<CancelVoteData>> => {
	const mutationOptions: MutationOptions<
		CancelVoteResponse,
		CancelVoteError,
		Options<CancelVoteData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await cancelVote({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getVotingDashboardQueryKey = (options?: Options<GetVotingDashboardData>) =>
	createQueryKey('getVotingDashboard', options);

/**
 * Get the organizer voting dashboard
 *
 * Voting time range, the leading participant in each votable nomination, and the size of the prize-draw pool. Requires voting:manage.
 */
export const getVotingDashboardOptions = (options?: Options<GetVotingDashboardData>) =>
	queryOptions<
		GetVotingDashboardResponse,
		GetVotingDashboardError,
		GetVotingDashboardResponse,
		ReturnType<typeof getVotingDashboardQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getVotingDashboard({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getVotingDashboardQueryKey(options)
	});

/**
 * Set voting time range
 *
 * Sets the time range during which visitors can vote. Requires voting:manage.
 */
export const setVotingTimeRangeMutation = (
	options?: Partial<Options<SetVotingTimeRangeData>>
): MutationOptions<
	SetVotingTimeRangeResponse,
	SetVotingTimeRangeError,
	Options<SetVotingTimeRangeData>
> => {
	const mutationOptions: MutationOptions<
		SetVotingTimeRangeResponse,
		SetVotingTimeRangeError,
		Options<SetVotingTimeRangeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await setVotingTimeRange({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Draw a random voting-contest winner
 *
 * Picks one random user who voted in every votable nomination. Stateless — repeated draws may return the same user. Requires voting:manage.
 */
export const drawVotingContestWinnerMutation = (
	options?: Partial<Options<DrawVotingContestWinnerData>>
): MutationOptions<
	DrawVotingContestWinnerResponse,
	DrawVotingContestWinnerError,
	Options<DrawVotingContestWinnerData>
> => {
	const mutationOptions: MutationOptions<
		DrawVotingContestWinnerResponse,
		DrawVotingContestWinnerError,
		Options<DrawVotingContestWinnerData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await drawVotingContestWinner({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Process TicketsCloud webhook
 *
 * Handles incoming webhook events from TicketsCloud ticketing system.
 */
export const processTcloudOrderMutation = (
	options?: Partial<Options<ProcessTcloudOrderData>>
): MutationOptions<
	ProcessTcloudOrderResponse,
	ProcessTcloudOrderError,
	Options<ProcessTcloudOrderData>
> => {
	const mutationOptions: MutationOptions<
		ProcessTcloudOrderResponse,
		ProcessTcloudOrderError,
		Options<ProcessTcloudOrderData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await processTcloudOrder({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listUserNotificationsQueryKey = (options?: Options<ListUserNotificationsData>) =>
	createQueryKey('listUserNotifications', options);

/**
 * List user notifications
 *
 * Returns a paginated list of notifications for the authenticated user.
 */
export const listUserNotificationsOptions = (options?: Options<ListUserNotificationsData>) =>
	queryOptions<
		ListUserNotificationsResponse,
		ListUserNotificationsError,
		ListUserNotificationsResponse,
		ReturnType<typeof listUserNotificationsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listUserNotifications({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listUserNotificationsQueryKey(options)
	});

export const listUserNotificationsInfiniteQueryKey = (
	options?: Options<ListUserNotificationsData>
): QueryKey<Options<ListUserNotificationsData>> =>
	createQueryKey('listUserNotifications', options, true);

/**
 * List user notifications
 *
 * Returns a paginated list of notifications for the authenticated user.
 */
export const listUserNotificationsInfiniteOptions = (
	options?: Options<ListUserNotificationsData>
) => {
	const opts = infiniteQueryOptions<
		ListUserNotificationsResponse,
		ListUserNotificationsError,
		InfiniteData<ListUserNotificationsResponse>,
		QueryKey<Options<ListUserNotificationsData>>,
		| number
		| Pick<QueryKey<Options<ListUserNotificationsData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ListUserNotificationsData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam
								}
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await listUserNotifications({
					...options,
					...params,
					signal,
					throwOnError: true
				});
				return data;
			},
			queryKey: listUserNotificationsInfiniteQueryKey(options)
		}
	);
	return opts as Omit<typeof opts, 'initialData'>;
};

export const countUnreadNotificationsQueryKey = (options?: Options<CountUnreadNotificationsData>) =>
	createQueryKey('countUnreadNotifications', options);

/**
 * Count unread notifications
 *
 * Returns the total number of unread notifications for the authenticated user, independent of any page size — the bell badge is driven by this.
 */
export const countUnreadNotificationsOptions = (options?: Options<CountUnreadNotificationsData>) =>
	queryOptions<
		CountUnreadNotificationsResponse,
		CountUnreadNotificationsError,
		CountUnreadNotificationsResponse,
		ReturnType<typeof countUnreadNotificationsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await countUnreadNotifications({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: countUnreadNotificationsQueryKey(options)
	});

/**
 * Mark all notifications as read
 *
 * Marks all unread notifications for the authenticated user as read.
 */
export const markAllNotificationsReadMutation = (
	options?: Partial<Options<MarkAllNotificationsReadData>>
): MutationOptions<
	MarkAllNotificationsReadResponse,
	MarkAllNotificationsReadError,
	Options<MarkAllNotificationsReadData>
> => {
	const mutationOptions: MutationOptions<
		MarkAllNotificationsReadResponse,
		MarkAllNotificationsReadError,
		Options<MarkAllNotificationsReadData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await markAllNotificationsRead({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Mark specific notifications as read
 *
 * Marks the given notifications as read for the authenticated user. Used when opening the notifications panel or page marks the visible items seen.
 */
export const markNotificationsReadMutation = (
	options?: Partial<Options<MarkNotificationsReadData>>
): MutationOptions<
	MarkNotificationsReadResponse,
	MarkNotificationsReadError,
	Options<MarkNotificationsReadData>
> => {
	const mutationOptions: MutationOptions<
		MarkNotificationsReadResponse,
		MarkNotificationsReadError,
		Options<MarkNotificationsReadData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await markNotificationsRead({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Send test notification
 *
 * Creates a test notification for the authenticated user and sends it through all connected channels.
 */
export const sendTestNotificationMutation = (
	options?: Partial<Options<SendTestNotificationData>>
): MutationOptions<
	SendTestNotificationResponse,
	SendTestNotificationError,
	Options<SendTestNotificationData>
> => {
	const mutationOptions: MutationOptions<
		SendTestNotificationResponse,
		SendTestNotificationError,
		Options<SendTestNotificationData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await sendTestNotification({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listBroadcastsQueryKey = (options?: Options<ListBroadcastsData>) =>
	createQueryKey('listBroadcasts', options);

/**
 * List broadcasts
 *
 * Returns organizer broadcasts newest-first, paginated. Schedule-change fan-outs are excluded — only role-targeted broadcasts appear.
 */
export const listBroadcastsOptions = (options?: Options<ListBroadcastsData>) =>
	queryOptions<
		ListBroadcastsResponse,
		ListBroadcastsError,
		ListBroadcastsResponse,
		ReturnType<typeof listBroadcastsQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listBroadcasts({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listBroadcastsQueryKey(options)
	});

export const listBroadcastsInfiniteQueryKey = (
	options?: Options<ListBroadcastsData>
): QueryKey<Options<ListBroadcastsData>> => createQueryKey('listBroadcasts', options, true);

/**
 * List broadcasts
 *
 * Returns organizer broadcasts newest-first, paginated. Schedule-change fan-outs are excluded — only role-targeted broadcasts appear.
 */
export const listBroadcastsInfiniteOptions = (options?: Options<ListBroadcastsData>) => {
	const opts = infiniteQueryOptions<
		ListBroadcastsResponse,
		ListBroadcastsError,
		InfiniteData<ListBroadcastsResponse>,
		QueryKey<Options<ListBroadcastsData>>,
		number | Pick<QueryKey<Options<ListBroadcastsData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ListBroadcastsData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam
								}
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await listBroadcasts({
					...options,
					...params,
					signal,
					throwOnError: true
				});
				return data;
			},
			queryKey: listBroadcastsInfiniteQueryKey(options)
		}
	);
	return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Send broadcast notification
 *
 * Creates a new mailing broadcast for specified user roles.
 */
export const sendBroadcastMutation = (
	options?: Partial<Options<SendBroadcastData>>
): MutationOptions<SendBroadcastResponse, SendBroadcastError, Options<SendBroadcastData>> => {
	const mutationOptions: MutationOptions<
		SendBroadcastResponse,
		SendBroadcastError,
		Options<SendBroadcastData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await sendBroadcast({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Cancel a mailing
 *
 * Cancels a mailing: marks it cancelled and deletes its still-undelivered notifications. Messages already delivered to a device cannot be recalled.
 */
export const cancelMailingMutation = (
	options?: Partial<Options<CancelMailingData>>
): MutationOptions<CancelMailingResponse, CancelMailingError, Options<CancelMailingData>> => {
	const mutationOptions: MutationOptions<
		CancelMailingResponse,
		CancelMailingError,
		Options<CancelMailingData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await cancelMailing({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Unsubscribe from push notifications
 *
 * Removes a push subscription endpoint for the authenticated user.
 */
export const unsubscribeMutation = (
	options?: Partial<Options<UnsubscribeData>>
): MutationOptions<UnsubscribeResponse, UnsubscribeError, Options<UnsubscribeData>> => {
	const mutationOptions: MutationOptions<
		UnsubscribeResponse,
		UnsubscribeError,
		Options<UnsubscribeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await unsubscribe({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const checkSubscriptionQueryKey = (options: Options<CheckSubscriptionData>) =>
	createQueryKey('checkSubscription', options);

/**
 * Check push subscription
 *
 * Reports whether the given endpoint is registered for the authenticated user. The client only needs this yes/no answer for its own device, so the full subscription list (incl. its keys) is not exposed.
 */
export const checkSubscriptionOptions = (options: Options<CheckSubscriptionData>) =>
	queryOptions<
		CheckSubscriptionResponse,
		CheckSubscriptionError,
		CheckSubscriptionResponse,
		ReturnType<typeof checkSubscriptionQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await checkSubscription({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: checkSubscriptionQueryKey(options)
	});

/**
 * Subscribe to push notifications
 *
 * Registers a push subscription endpoint for the authenticated user's device.
 */
export const subscribeMutation = (
	options?: Partial<Options<SubscribeData>>
): MutationOptions<SubscribeResponse, SubscribeError, Options<SubscribeData>> => {
	const mutationOptions: MutationOptions<
		SubscribeResponse,
		SubscribeError,
		Options<SubscribeData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await subscribe({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listFeedbackQueryKey = (options?: Options<ListFeedbackData>) =>
	createQueryKey('listFeedback', options);

/**
 * List app feedback
 *
 * Returns a paginated list of feedback submitted by users, newest first. Requires the feedback:read permission.
 */
export const listFeedbackOptions = (options?: Options<ListFeedbackData>) =>
	queryOptions<
		ListFeedbackResponse,
		ListFeedbackError,
		ListFeedbackResponse,
		ReturnType<typeof listFeedbackQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listFeedback({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listFeedbackQueryKey(options)
	});

export const listFeedbackInfiniteQueryKey = (
	options?: Options<ListFeedbackData>
): QueryKey<Options<ListFeedbackData>> => createQueryKey('listFeedback', options, true);

/**
 * List app feedback
 *
 * Returns a paginated list of feedback submitted by users, newest first. Requires the feedback:read permission.
 */
export const listFeedbackInfiniteOptions = (options?: Options<ListFeedbackData>) => {
	const opts = infiniteQueryOptions<
		ListFeedbackResponse,
		ListFeedbackError,
		InfiniteData<ListFeedbackResponse>,
		QueryKey<Options<ListFeedbackData>>,
		number | Pick<QueryKey<Options<ListFeedbackData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ListFeedbackData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam
								}
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await listFeedback({
					...options,
					...params,
					signal,
					throwOnError: true
				});
				return data;
			},
			queryKey: listFeedbackInfiniteQueryKey(options)
		}
	);
	return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Submit app feedback
 *
 * Submits free-text feedback about the app from the current user.
 */
export const submitFeedbackMutation = (
	options?: Partial<Options<SubmitFeedbackData>>
): MutationOptions<SubmitFeedbackResponse, SubmitFeedbackError, Options<SubmitFeedbackData>> => {
	const mutationOptions: MutationOptions<
		SubmitFeedbackResponse,
		SubmitFeedbackError,
		Options<SubmitFeedbackData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await submitFeedback({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

/**
 * Generate tickets
 *
 * Generates a batch of new tickets for the given role. Requires the 'tickets:generate' permission. Returns the created barcodes.
 */
export const generateTicketsMutation = (
	options?: Partial<Options<GenerateTicketsData>>
): MutationOptions<GenerateTicketsResponse, GenerateTicketsError, Options<GenerateTicketsData>> => {
	const mutationOptions: MutationOptions<
		GenerateTicketsResponse,
		GenerateTicketsError,
		Options<GenerateTicketsData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await generateTickets({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const getSyncSourcesQueryKey = (options?: Options<GetSyncSourcesData>) =>
	createQueryKey('getSyncSources', options);

/**
 * List sync sources with their last run
 *
 * Returns every vendor sync source, whether it is configured for this deployment, and its most recent run. Requires the 'sync:run' permission.
 */
export const getSyncSourcesOptions = (options?: Options<GetSyncSourcesData>) =>
	queryOptions<
		GetSyncSourcesResponse,
		GetSyncSourcesError,
		GetSyncSourcesResponse,
		ReturnType<typeof getSyncSourcesQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getSyncSources({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getSyncSourcesQueryKey(options)
	});

/**
 * Request a sync
 *
 * Queues a sync of the given source and returns immediately with the created run. The work runs in the stream service, so progress arrives over SSE ('sync_run_updated') and the run's final state is readable from GET /sync/sources. Requires the 'sync:run' permission.
 */
export const requestSyncMutation = (
	options?: Partial<Options<RequestSyncData>>
): MutationOptions<RequestSyncResponse, RequestSyncError, Options<RequestSyncData>> => {
	const mutationOptions: MutationOptions<
		RequestSyncResponse,
		RequestSyncError,
		Options<RequestSyncData>
	> = {
		mutationFn: async (fnOptions) => {
			const { data } = await requestSync({
				...options,
				...fnOptions,
				throwOnError: true
			});
			return data;
		}
	};
	return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
	createQueryKey('listUsers', options);

/**
 * List users
 *
 * Paginated, searchable directory of all users. Search matches a case-insensitive substring of the username or email. Requires users:read.
 */
export const listUsersOptions = (options?: Options<ListUsersData>) =>
	queryOptions<
		ListUsersResponse,
		ListUsersError,
		ListUsersResponse,
		ReturnType<typeof listUsersQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await listUsers({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: listUsersQueryKey(options)
	});

export const listUsersInfiniteQueryKey = (
	options?: Options<ListUsersData>
): QueryKey<Options<ListUsersData>> => createQueryKey('listUsers', options, true);

/**
 * List users
 *
 * Paginated, searchable directory of all users. Search matches a case-insensitive substring of the username or email. Requires users:read.
 */
export const listUsersInfiniteOptions = (options?: Options<ListUsersData>) => {
	const opts = infiniteQueryOptions<
		ListUsersResponse,
		ListUsersError,
		InfiniteData<ListUsersResponse>,
		QueryKey<Options<ListUsersData>>,
		number | Pick<QueryKey<Options<ListUsersData>>[0], 'body' | 'headers' | 'path' | 'query'>
	>(
		// @ts-ignore
		{
			queryFn: async ({ pageParam, queryKey, signal }) => {
				// @ts-ignore
				const page: Pick<
					QueryKey<Options<ListUsersData>>[0],
					'body' | 'headers' | 'path' | 'query'
				> =
					typeof pageParam === 'object'
						? pageParam
						: {
								query: {
									offset: pageParam
								}
							};
				const params = createInfiniteParams(queryKey, page);
				const { data } = await listUsers({
					...options,
					...params,
					signal,
					throwOnError: true
				});
				return data;
			},
			queryKey: listUsersInfiniteQueryKey(options)
		}
	);
	return opts as Omit<typeof opts, 'initialData'>;
};

export const countOnlineUsersQueryKey = (options?: Options<CountOnlineUsersData>) =>
	createQueryKey('countOnlineUsers', options);

/**
 * Count online users
 *
 * How many users hold a live connection right now, for the organiser dashboard. Approximate and ephemeral. Any authenticated user.
 */
export const countOnlineUsersOptions = (options?: Options<CountOnlineUsersData>) =>
	queryOptions<
		CountOnlineUsersResponse,
		CountOnlineUsersError,
		CountOnlineUsersResponse,
		ReturnType<typeof countOnlineUsersQueryKey>
	>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await countOnlineUsers({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: countOnlineUsersQueryKey(options)
	});

export const getUserQueryKey = (options: Options<GetUserData>) =>
	createQueryKey('getUser', options);

/**
 * Get user details
 *
 * Profile basics and linked external accounts for one user. Requires users:read.
 */
export const getUserOptions = (options: Options<GetUserData>) =>
	queryOptions<GetUserResponse, GetUserError, GetUserResponse, ReturnType<typeof getUserQueryKey>>({
		queryFn: async ({ queryKey, signal }) => {
			const { data } = await getUser({
				...options,
				...queryKey[0],
				signal,
				throwOnError: true
			});
			return data;
		},
		queryKey: getUserQueryKey(options)
	});
