from typing import Protocol

from fanfan.application.dto.mailing import MailingDTO
from fanfan.core.models.mailing import Mailing
from fanfan.core.vo.mailing import MailingId


class MailingRepository(Protocol):
    async def add(self, mailing: Mailing) -> None: ...
    async def get(self, mailing_id: MailingId) -> Mailing | None: ...
    async def save(self, mailing: Mailing) -> None: ...
    async def increment_sent(self, mailing_id: MailingId) -> None: ...
    async def read_mailing(self, mailing_id: MailingId) -> MailingDTO | None: ...
