from typing import Protocol

from fanfan.core.models.nomination import Nomination


class NominationRepository(Protocol):
    async def add(self, nomination: Nomination) -> None: ...
    async def get_by_cosplay2_id(self, cosplay2_id: int) -> Nomination | None: ...
    async def save(self, nomination: Nomination) -> None: ...
    async def count_votable(self) -> int: ...
    async def list_cosplay2_ids(self) -> list[int]: ...
    async def delete_by_cosplay2_ids(self, cosplay2_ids: list[int]) -> None: ...
