from typing import Protocol

from fanfan.application.dto.nomination import NominationVotingDTO
from fanfan.application.dto.page import Pagination
from fanfan.core.models.nomination import Nomination
from fanfan.core.vo.nomination import NominationCode
from fanfan.core.vo.user import UserId


class NominationRepository(Protocol):
    async def add(self, nomination: Nomination) -> None: ...
    async def get_by_cosplay2_id(self, cosplay2_id: int) -> Nomination | None: ...
    async def save(self, nomination: Nomination) -> None: ...
    async def count_votable(self) -> int: ...
    async def list_cosplay2_ids(self) -> list[int]: ...
    async def delete_by_cosplay2_ids(self, cosplay2_ids: list[int]) -> None: ...
    async def read_voting_dto(
        self, nomination_code: NominationCode, user_id: UserId
    ) -> NominationVotingDTO | None: ...
    async def read_list_votable_nominations(
        self,
        user_id: UserId | None = None,
        pagination: Pagination | None = None,
    ) -> list[NominationVotingDTO]: ...
