from typing import Protocol

from fanfan.core.models.participant import Participant
from fanfan.core.vo.participant import ParticipantId


class ParticipantRepository(Protocol):
    async def add(self, participant: Participant) -> None: ...
    async def get(self, participant_id: ParticipantId) -> Participant | None: ...
    async def get_by_cosplay2_id(self, cosplay2_id: int) -> Participant | None: ...
    async def save(self, participant: Participant) -> None: ...
    async def delete(self, participant: Participant) -> None: ...
    async def list_cosplay2_ids(self) -> list[int]: ...
    async def delete_by_cosplay2_ids(self, cosplay2_ids: list[int]) -> None: ...
