from typing import Protocol

from fanfan.core.models.push_subscription import PushSubscription
from fanfan.core.vo.user import UserId


class PushSubscriptionRepository(Protocol):
    async def add(self, model: PushSubscription) -> None: ...
    async def get_by_endpoint(self, endpoint: str) -> PushSubscription | None: ...
    async def list_by_user(self, user_id: UserId) -> list[PushSubscription]: ...
    async def delete(self, model: PushSubscription) -> None: ...
