from typing import Protocol

from fanfan.core.models.schedule_event import ScheduleEvent
from fanfan.core.vo.schedule_event import ScheduleEventId


class ScheduleEventRepository(Protocol):
    async def add(self, event: ScheduleEvent) -> None: ...
    async def get_by_id(self, event_id: ScheduleEventId) -> ScheduleEvent | None: ...
    async def get_by_queue(self, queue: int) -> ScheduleEvent | None: ...
    async def get_current(self) -> ScheduleEvent | None: ...
    async def get_next(self) -> ScheduleEvent | None: ...
    async def list_all(self) -> list[ScheduleEvent]: ...
    async def get_next_by_order(self, order: float) -> ScheduleEvent | None: ...
    async def get_previous_by_order(self, order: float) -> ScheduleEvent | None: ...
    async def save(self, event: ScheduleEvent) -> None: ...
    async def delete(self, event: ScheduleEvent) -> None: ...
