from typing import Protocol

from fanfan.core.models.user import User
from fanfan.core.vo.user import UserId


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UserId) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_pending_email(self, email: str) -> User | None: ...
    async def get_by_any_email(self, email: str) -> User | None: ...
    async def get_by_social_id(
        self,
        provider_name: str,
        provider_account_id: str,
    ) -> User | None: ...
    async def save(self, user: User) -> None: ...
