from typing import Protocol

from fanfan.core.models.vote import Vote
from fanfan.core.vo.nomination import NominationId
from fanfan.core.vo.user import UserId


class VoteRepository(Protocol):
    async def add(self, vote: Vote) -> None: ...
    async def get_user_vote_by_nomination(
        self, nomination_id: NominationId, user_id: UserId
    ) -> Vote | None: ...
    async def delete(self, vote: Vote) -> None: ...
    async def delete_all_user_votes(self, user_id: UserId) -> None: ...
    async def count_user_votes(self, user_id: UserId) -> int: ...
